"""Auto-generated. Do not edit by hand; regenerate from data/items.yaml."""

from BaseClasses import ItemClassification

BASE_ID = 5750000

ITEM_NAME_TO_ID: dict[str, int] = {
    'Alohomora': 5750001,
    'Diffindo': 5750002,
    'Flipendo': 5750003,
    'Lumos': 5750004,
    'Rictusempra': 5750005,
    'Skurge': 5750006,
    'Spongify': 5750007,
    'Nimbus 2001': 5750008,
    'Quidditch Armour': 5750009,
    'Card - Agrippa': 5750100,
    'Card - Alderton': 5750101,
    'Card - Barbary': 5750102,
    'Card - Barkwith': 5750103,
    'Card - Belby': 5750104,
    'Card - Blane': 5750105,
    'Card - Bloxam': 5750106,
    'Card - Bonham': 5750107,
    'Card - Catchlove': 5750108,
    'Card - Elphick': 5750109,
    'Card - Ethelred': 5750110,
    'Card - Fancourt': 5750111,
    'Card - Goshawk': 5750112,
    'Card - Graves': 5750113,
    'Card - Gunhilda': 5750114,
    'Card - Hipworth': 5750115,
    'Card - Kegg': 5750116,
    'Card - Ketteridge': 5750117,
    'Card - Marjoribanks': 5750118,
    'Card - Merlin': 5750119,
    'Card - Merwyn': 5750120,
    'Card - Muldoon': 5750121,
    'Card - Ollerton': 5750122,
    'Card - Peakes': 5750123,
    'Card - Pilliwickle': 5750124,
    'Card - Platt': 5750125,
    'Card - Plumpton': 5750126,
    'Card - Po': 5750127,
    'Card - Pokeby': 5750128,
    'Card - Sawbridge': 5750129,
    'Card - Scamander': 5750130,
    'Card - Starkey': 5750131,
    'Card - Stroulger': 5750132,
    'Card - Stump': 5750133,
    'Card - Sweeting': 5750134,
    'Card - Sykes': 5750135,
    'Card - Thruston': 5750136,
    'Card - Toke': 5750137,
    'Card - Twonk': 5750138,
    'Card - Ulric': 5750139,
    'Card - Vablatsky': 5750140,
    'Card - Waffling': 5750141,
    'Card - Wagtail': 5750142,
    'Card - Warbeck': 5750143,
    'Card - Wellbeloved': 5750144,
    'Card - Wenlock': 5750145,
    'Card - Whitehorn': 5750146,
    'Card - Wintringham': 5750147,
    'Card - Withers': 5750148,
    'Card - Woodcroft': 5750149,
    'Card - Andros': 5750150,
    'Card - Beamish': 5750151,
    'Card - Chittock': 5750152,
    'Card - Circe': 5750153,
    'Card - Clagg': 5750154,
    'Card - Cliodne': 5750155,
    'Card - Cronk': 5750156,
    'Card - Crumb': 5750157,
    'Card - Dodderidge': 5750158,
    'Card - Duke': 5750159,
    'Card - Fay': 5750160,
    'Card - Fulbert': 5750161,
    'Card - Furmage': 5750162,
    'Card - Gregory': 5750163,
    'Card - Grunnion': 5750164,
    'Card - Jones': 5750165,
    'Card - Lufkin': 5750166,
    'Card - Maeve': 5750167,
    'Card - Montmorency': 5750168,
    'Card - Mopsus': 5750169,
    'Card - Nutcombe': 5750170,
    'Card - Oglethorpe': 5750171,
    'Card - Oldridge': 5750172,
    'Card - Oliphant': 5750173,
    'Card - Plunkett': 5750174,
    'Card - Rastrick': 5750175,
    'Card - Shimpling': 5750176,
    'Card - Shingleton': 5750177,
    'Card - Smethwyck': 5750178,
    'Card - Stalk': 5750179,
    'Card - Summerbee': 5750180,
    'Card - Thurkell': 5750181,
    'Card - Toothill': 5750182,
    'Card - Tremlett': 5750183,
    'Card - Tugwood': 5750184,
    'Card - Wadcock': 5750185,
    'Card - Wendelin': 5750186,
    'Card - Wildsmith': 5750187,
    'Card - Wright': 5750188,
    'Card - Youdle': 5750189,
    'Card - Bott': 5750190,
    'Card - Dumbledore': 5750191,
    'Card - Gryffindor': 5750192,
    'Card - Herpo': 5750193,
    'Card - Hufflepuff': 5750194,
    'Card - Knightley': 5750195,
    'Card - Paracelsus': 5750196,
    'Card - Pinkstone': 5750197,
    'Card - Potter': 5750198,
    'Card - Ravenclaw': 5750199,
    'Card - Slytherin': 5750200,
    'Small Pile of Beans': 5750300,
    'Medium Pile of Beans': 5750301,
    'Large Pile of Beans': 5750302,
    'Massive Pile of Beans': 5750303,
    'Wiggenweld Potion': 5750304,
    'Wiggentree Bark': 5750305,
    'Flobberworm Mucous': 5750306,
    'Chocolate Frog': 5750307,
}

ITEM_CLASSIFICATIONS: dict[str, ItemClassification] = {
    'Alohomora': ItemClassification.progression,
    'Diffindo': ItemClassification.progression,
    'Flipendo': ItemClassification.progression,
    'Lumos': ItemClassification.progression,
    'Rictusempra': ItemClassification.progression,
    'Skurge': ItemClassification.progression,
    'Spongify': ItemClassification.progression,
    'Nimbus 2001': ItemClassification.useful,
    'Quidditch Armour': ItemClassification.useful,
    'Card - Agrippa': ItemClassification.useful,
    'Card - Alderton': ItemClassification.useful,
    'Card - Barbary': ItemClassification.useful,
    'Card - Barkwith': ItemClassification.useful,
    'Card - Belby': ItemClassification.useful,
    'Card - Blane': ItemClassification.useful,
    'Card - Bloxam': ItemClassification.useful,
    'Card - Bonham': ItemClassification.useful,
    'Card - Catchlove': ItemClassification.useful,
    'Card - Elphick': ItemClassification.useful,
    'Card - Ethelred': ItemClassification.useful,
    'Card - Fancourt': ItemClassification.useful,
    'Card - Goshawk': ItemClassification.useful,
    'Card - Graves': ItemClassification.useful,
    'Card - Gunhilda': ItemClassification.useful,
    'Card - Hipworth': ItemClassification.useful,
    'Card - Kegg': ItemClassification.useful,
    'Card - Ketteridge': ItemClassification.useful,
    'Card - Marjoribanks': ItemClassification.useful,
    'Card - Merlin': ItemClassification.useful,
    'Card - Merwyn': ItemClassification.useful,
    'Card - Muldoon': ItemClassification.useful,
    'Card - Ollerton': ItemClassification.useful,
    'Card - Peakes': ItemClassification.useful,
    'Card - Pilliwickle': ItemClassification.useful,
    'Card - Platt': ItemClassification.useful,
    'Card - Plumpton': ItemClassification.useful,
    'Card - Po': ItemClassification.useful,
    'Card - Pokeby': ItemClassification.useful,
    'Card - Sawbridge': ItemClassification.useful,
    'Card - Scamander': ItemClassification.useful,
    'Card - Starkey': ItemClassification.useful,
    'Card - Stroulger': ItemClassification.useful,
    'Card - Stump': ItemClassification.useful,
    'Card - Sweeting': ItemClassification.useful,
    'Card - Sykes': ItemClassification.useful,
    'Card - Thruston': ItemClassification.useful,
    'Card - Toke': ItemClassification.useful,
    'Card - Twonk': ItemClassification.useful,
    'Card - Ulric': ItemClassification.useful,
    'Card - Vablatsky': ItemClassification.useful,
    'Card - Waffling': ItemClassification.useful,
    'Card - Wagtail': ItemClassification.useful,
    'Card - Warbeck': ItemClassification.useful,
    'Card - Wellbeloved': ItemClassification.useful,
    'Card - Wenlock': ItemClassification.useful,
    'Card - Whitehorn': ItemClassification.useful,
    'Card - Wintringham': ItemClassification.useful,
    'Card - Withers': ItemClassification.useful,
    'Card - Woodcroft': ItemClassification.useful,
    'Card - Andros': ItemClassification.progression_skip_balancing,
    'Card - Beamish': ItemClassification.progression_skip_balancing,
    'Card - Chittock': ItemClassification.progression_skip_balancing,
    'Card - Circe': ItemClassification.progression_skip_balancing,
    'Card - Clagg': ItemClassification.progression_skip_balancing,
    'Card - Cliodne': ItemClassification.progression_skip_balancing,
    'Card - Cronk': ItemClassification.progression_skip_balancing,
    'Card - Crumb': ItemClassification.progression_skip_balancing,
    'Card - Dodderidge': ItemClassification.progression_skip_balancing,
    'Card - Duke': ItemClassification.progression_skip_balancing,
    'Card - Fay': ItemClassification.progression_skip_balancing,
    'Card - Fulbert': ItemClassification.progression_skip_balancing,
    'Card - Furmage': ItemClassification.progression_skip_balancing,
    'Card - Gregory': ItemClassification.progression_skip_balancing,
    'Card - Grunnion': ItemClassification.progression_skip_balancing,
    'Card - Jones': ItemClassification.progression_skip_balancing,
    'Card - Lufkin': ItemClassification.progression_skip_balancing,
    'Card - Maeve': ItemClassification.progression_skip_balancing,
    'Card - Montmorency': ItemClassification.progression_skip_balancing,
    'Card - Mopsus': ItemClassification.progression_skip_balancing,
    'Card - Nutcombe': ItemClassification.progression_skip_balancing,
    'Card - Oglethorpe': ItemClassification.progression_skip_balancing,
    'Card - Oldridge': ItemClassification.progression_skip_balancing,
    'Card - Oliphant': ItemClassification.progression_skip_balancing,
    'Card - Plunkett': ItemClassification.progression_skip_balancing,
    'Card - Rastrick': ItemClassification.progression_skip_balancing,
    'Card - Shimpling': ItemClassification.progression_skip_balancing,
    'Card - Shingleton': ItemClassification.progression_skip_balancing,
    'Card - Smethwyck': ItemClassification.progression_skip_balancing,
    'Card - Stalk': ItemClassification.progression_skip_balancing,
    'Card - Summerbee': ItemClassification.progression_skip_balancing,
    'Card - Thurkell': ItemClassification.progression_skip_balancing,
    'Card - Toothill': ItemClassification.progression_skip_balancing,
    'Card - Tremlett': ItemClassification.progression_skip_balancing,
    'Card - Tugwood': ItemClassification.progression_skip_balancing,
    'Card - Wadcock': ItemClassification.progression_skip_balancing,
    'Card - Wendelin': ItemClassification.progression_skip_balancing,
    'Card - Wildsmith': ItemClassification.progression_skip_balancing,
    'Card - Wright': ItemClassification.progression_skip_balancing,
    'Card - Youdle': ItemClassification.progression_skip_balancing,
    'Card - Bott': ItemClassification.useful,
    'Card - Dumbledore': ItemClassification.useful,
    'Card - Gryffindor': ItemClassification.useful,
    'Card - Herpo': ItemClassification.useful,
    'Card - Hufflepuff': ItemClassification.useful,
    'Card - Knightley': ItemClassification.useful,
    'Card - Paracelsus': ItemClassification.useful,
    'Card - Pinkstone': ItemClassification.useful,
    'Card - Potter': ItemClassification.useful,
    'Card - Ravenclaw': ItemClassification.useful,
    'Card - Slytherin': ItemClassification.useful,
    'Small Pile of Beans': ItemClassification.filler,
    'Medium Pile of Beans': ItemClassification.filler,
    'Large Pile of Beans': ItemClassification.filler,
    'Massive Pile of Beans': ItemClassification.filler,
    'Wiggenweld Potion': ItemClassification.filler,
    'Wiggentree Bark': ItemClassification.filler,
    'Flobberworm Mucous': ItemClassification.filler,
    'Chocolate Frog': ItemClassification.filler,
}

ITEM_GROUPS: dict[str, list[str]] = {
    'Spells': ['Alohomora', 'Diffindo', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge', 'Spongify'],
    'Key Items': [],
    'Equipment': ['Nimbus 2001', 'Quidditch Armour'],
    'Cards (Bronze)': ['Card - Agrippa', 'Card - Alderton', 'Card - Barbary', 'Card - Barkwith', 'Card - Belby', 'Card - Blane', 'Card - Bloxam', 'Card - Bonham', 'Card - Catchlove', 'Card - Elphick', 'Card - Ethelred', 'Card - Fancourt', 'Card - Goshawk', 'Card - Graves', 'Card - Gunhilda', 'Card - Hipworth', 'Card - Kegg', 'Card - Ketteridge', 'Card - Marjoribanks', 'Card - Merlin', 'Card - Merwyn', 'Card - Muldoon', 'Card - Ollerton', 'Card - Peakes', 'Card - Pilliwickle', 'Card - Platt', 'Card - Plumpton', 'Card - Po', 'Card - Pokeby', 'Card - Sawbridge', 'Card - Scamander', 'Card - Starkey', 'Card - Stroulger', 'Card - Stump', 'Card - Sweeting', 'Card - Sykes', 'Card - Thruston', 'Card - Toke', 'Card - Twonk', 'Card - Ulric', 'Card - Vablatsky', 'Card - Waffling', 'Card - Wagtail', 'Card - Warbeck', 'Card - Wellbeloved', 'Card - Wenlock', 'Card - Whitehorn', 'Card - Wintringham', 'Card - Withers', 'Card - Woodcroft'],
    'Cards (Silver)': ['Card - Andros', 'Card - Beamish', 'Card - Chittock', 'Card - Circe', 'Card - Clagg', 'Card - Cliodne', 'Card - Cronk', 'Card - Crumb', 'Card - Dodderidge', 'Card - Duke', 'Card - Fay', 'Card - Fulbert', 'Card - Furmage', 'Card - Gregory', 'Card - Grunnion', 'Card - Jones', 'Card - Lufkin', 'Card - Maeve', 'Card - Montmorency', 'Card - Mopsus', 'Card - Nutcombe', 'Card - Oglethorpe', 'Card - Oldridge', 'Card - Oliphant', 'Card - Plunkett', 'Card - Rastrick', 'Card - Shimpling', 'Card - Shingleton', 'Card - Smethwyck', 'Card - Stalk', 'Card - Summerbee', 'Card - Thurkell', 'Card - Toothill', 'Card - Tremlett', 'Card - Tugwood', 'Card - Wadcock', 'Card - Wendelin', 'Card - Wildsmith', 'Card - Wright', 'Card - Youdle'],
    'Cards (Gold)': ['Card - Bott', 'Card - Dumbledore', 'Card - Gryffindor', 'Card - Herpo', 'Card - Hufflepuff', 'Card - Knightley', 'Card - Paracelsus', 'Card - Pinkstone', 'Card - Potter', 'Card - Ravenclaw', 'Card - Slytherin'],
    'Filler': ['Small Pile of Beans', 'Medium Pile of Beans', 'Large Pile of Beans', 'Massive Pile of Beans', 'Wiggenweld Potion', 'Wiggentree Bark', 'Flobberworm Mucous', 'Chocolate Frog'],
}

FILLER_NAMES: list[str] = ['Small Pile of Beans', 'Medium Pile of Beans', 'Large Pile of Beans', 'Massive Pile of Beans', 'Wiggenweld Potion', 'Wiggentree Bark', 'Flobberworm Mucous', 'Chocolate Frog']

# Map UScript card class name → AP item display name. Used by the client
# when forwarding 'GRANT <classname>' messages to the mod for cards.
CARD_CLASS_TO_ITEM_NAME: dict[str, str] = {
    'WCAgrippa': 'Card - Agrippa',
    'WCAlderton': 'Card - Alderton',
    'WCBarbary': 'Card - Barbary',
    'WCBarkwith': 'Card - Barkwith',
    'WCBelby': 'Card - Belby',
    'WCBlane': 'Card - Blane',
    'WCBloxam': 'Card - Bloxam',
    'WCBonham': 'Card - Bonham',
    'WCCatchlove': 'Card - Catchlove',
    'WCElphick': 'Card - Elphick',
    'WCEthelred': 'Card - Ethelred',
    'WCFancourt': 'Card - Fancourt',
    'WCGoshawk': 'Card - Goshawk',
    'WCGraves': 'Card - Graves',
    'WCGunhilda': 'Card - Gunhilda',
    'WCHipworth': 'Card - Hipworth',
    'WCKegg': 'Card - Kegg',
    'WCKetteridge': 'Card - Ketteridge',
    'WCMarjoribanks': 'Card - Marjoribanks',
    'WCMerlin': 'Card - Merlin',
    'WCMerwyn': 'Card - Merwyn',
    'WCMuldoon': 'Card - Muldoon',
    'WCOllerton': 'Card - Ollerton',
    'WCPeakes': 'Card - Peakes',
    'WCPilliwickle': 'Card - Pilliwickle',
    'WCPlatt': 'Card - Platt',
    'WCPlumpton': 'Card - Plumpton',
    'WCPo': 'Card - Po',
    'WCPokeby': 'Card - Pokeby',
    'WCSawbridge': 'Card - Sawbridge',
    'WCScamander': 'Card - Scamander',
    'WCStarkey': 'Card - Starkey',
    'WCStroulger': 'Card - Stroulger',
    'WCStump': 'Card - Stump',
    'WCSweeting': 'Card - Sweeting',
    'WCSykes': 'Card - Sykes',
    'WCThruston': 'Card - Thruston',
    'WCToke': 'Card - Toke',
    'WCTwonk': 'Card - Twonk',
    'WCUlric': 'Card - Ulric',
    'WCVablatsky': 'Card - Vablatsky',
    'WCWaffling': 'Card - Waffling',
    'WCWagtail': 'Card - Wagtail',
    'WCWarbeck': 'Card - Warbeck',
    'WCWellbeloved': 'Card - Wellbeloved',
    'WCWenlock': 'Card - Wenlock',
    'WCWhitehorn': 'Card - Whitehorn',
    'WCWintringham': 'Card - Wintringham',
    'WCWithers': 'Card - Withers',
    'WCWoodcroft': 'Card - Woodcroft',
    'WCAndros': 'Card - Andros',
    'WCBeamish': 'Card - Beamish',
    'WCChittock': 'Card - Chittock',
    'WCCirce': 'Card - Circe',
    'WCClagg': 'Card - Clagg',
    'WCCliodne': 'Card - Cliodne',
    'WCCronk': 'Card - Cronk',
    'WCCrumb': 'Card - Crumb',
    'WCDodderidge': 'Card - Dodderidge',
    'WCDuke': 'Card - Duke',
    'WCFay': 'Card - Fay',
    'WCFulbert': 'Card - Fulbert',
    'WCFurmage': 'Card - Furmage',
    'WCGregory': 'Card - Gregory',
    'WCGrunnion': 'Card - Grunnion',
    'WCJones': 'Card - Jones',
    'WCLufkin': 'Card - Lufkin',
    'WCMaeve': 'Card - Maeve',
    'WCMontmorency': 'Card - Montmorency',
    'WCMopsus': 'Card - Mopsus',
    'WCNutcombe': 'Card - Nutcombe',
    'WCOglethorpe': 'Card - Oglethorpe',
    'WCOldridge': 'Card - Oldridge',
    'WCOliphant': 'Card - Oliphant',
    'WCPlunkett': 'Card - Plunkett',
    'WCRastrick': 'Card - Rastrick',
    'WCShimpling': 'Card - Shimpling',
    'WCShingleton': 'Card - Shingleton',
    'WCSmethwyck': 'Card - Smethwyck',
    'WCStalk': 'Card - Stalk',
    'WCSummerbee': 'Card - Summerbee',
    'WCThurkell': 'Card - Thurkell',
    'WCToothill': 'Card - Toothill',
    'WCTremlett': 'Card - Tremlett',
    'WCTugwood': 'Card - Tugwood',
    'WCWadcock': 'Card - Wadcock',
    'WCWendelin': 'Card - Wendelin',
    'WCWildsmith': 'Card - Wildsmith',
    'WCWright': 'Card - Wright',
    'WCYoudle': 'Card - Youdle',
    'WCBott': 'Card - Bott',
    'WCDumbledore': 'Card - Dumbledore',
    'WCGriffindor': 'Card - Gryffindor',
    'WCHerpo': 'Card - Herpo',
    'WCHufflepuff': 'Card - Hufflepuff',
    'WCKnightley': 'Card - Knightley',
    'WCParacelsus': 'Card - Paracelsus',
    'WCPinkstone': 'Card - Pinkstone',
    'WCPotter': 'Card - Potter',
    'WCRavenclaw': 'Card - Ravenclaw',
    'WCSlytherin': 'Card - Slytherin',
}
