"""Auto-generated. Do not edit by hand; regenerate from data/items.yaml."""

from BaseClasses import ItemClassification

BASE_ID = 5750000

ITEM_NAME_TO_ID: dict[str, int] = {
    'Alohomora': 5750001,
    'Diffindo': 5750002,
    'Flipendo': 5750003,
    'Lumos': 5750004,
    'Rictusempra': 5750005,
    'Skurge': 5750006,
    'Spongify': 5750007,
    'Chamber of Secrets Key': 5750250,
    'Spongify Classroom Key': 5750251,
    'Skurge Classroom Key': 5750252,
    'Rictusempra Classroom Key': 5750253,
    'Diffindo Classroom Key': 5750254,
    'Boomslang Level Key': 5750255,
    'Whomping Willow Key': 5750256,
    'Forbidden Forest Key': 5750257,
    'Slytherin Common Room Key': 5750258,
    'Goyle Level Key': 5750259,
    'Bicorn Level Key': 5750260,
    'Duelling Club Key': 5750261,
    'Quidditch Pitch Key': 5750262,
    'Nimbus 2001': 5750008,
    'Quidditch Armour': 5750009,
    'Bronze Card - Agrippa': 5750100,
    'Bronze Card - Alderton': 5750101,
    'Bronze Card - Barbary': 5750102,
    'Bronze Card - Barkwith': 5750103,
    'Bronze Card - Belby': 5750104,
    'Bronze Card - Blane': 5750105,
    'Bronze Card - Bloxam': 5750106,
    'Bronze Card - Bonham': 5750107,
    'Bronze Card - Catchlove': 5750108,
    'Bronze Card - Elphick': 5750109,
    'Bronze Card - Ethelred': 5750110,
    'Bronze Card - Fancourt': 5750111,
    'Bronze Card - Goshawk': 5750112,
    'Bronze Card - Graves': 5750113,
    'Bronze Card - Gunhilda': 5750114,
    'Bronze Card - Hipworth': 5750115,
    'Bronze Card - Kegg': 5750116,
    'Bronze Card - Ketteridge': 5750117,
    'Bronze Card - Marjoribanks': 5750118,
    'Bronze Card - Merlin': 5750119,
    'Bronze Card - Merwyn': 5750120,
    'Bronze Card - Muldoon': 5750121,
    'Bronze Card - Ollerton': 5750122,
    'Bronze Card - Peakes': 5750123,
    'Bronze Card - Pilliwickle': 5750124,
    'Bronze Card - Platt': 5750125,
    'Bronze Card - Plumpton': 5750126,
    'Bronze Card - Po': 5750127,
    'Bronze Card - Pokeby': 5750128,
    'Bronze Card - Sawbridge': 5750129,
    'Bronze Card - Scamander': 5750130,
    'Bronze Card - Starkey': 5750131,
    'Bronze Card - Stroulger': 5750132,
    'Bronze Card - Stump': 5750133,
    'Bronze Card - Sweeting': 5750134,
    'Bronze Card - Sykes': 5750135,
    'Bronze Card - Thruston': 5750136,
    'Bronze Card - Toke': 5750137,
    'Bronze Card - Twonk': 5750138,
    'Bronze Card - Ulric': 5750139,
    'Bronze Card - Vablatsky': 5750140,
    'Bronze Card - Waffling': 5750141,
    'Bronze Card - Wagtail': 5750142,
    'Bronze Card - Warbeck': 5750143,
    'Bronze Card - Wellbeloved': 5750144,
    'Bronze Card - Wenlock': 5750145,
    'Bronze Card - Whitehorn': 5750146,
    'Bronze Card - Wintringham': 5750147,
    'Bronze Card - Withers': 5750148,
    'Bronze Card - Woodcroft': 5750149,
    'Silver Card - Andros': 5750150,
    'Silver Card - Beamish': 5750151,
    'Silver Card - Chittock': 5750152,
    'Silver Card - Circe': 5750153,
    'Silver Card - Clagg': 5750154,
    'Silver Card - Cliodne': 5750155,
    'Silver Card - Cronk': 5750156,
    'Silver Card - Crumb': 5750157,
    'Silver Card - Dodderidge': 5750158,
    'Silver Card - Duke': 5750159,
    'Silver Card - Fay': 5750160,
    'Silver Card - Fulbert': 5750161,
    'Silver Card - Furmage': 5750162,
    'Silver Card - Gregory': 5750163,
    'Silver Card - Grunnion': 5750164,
    'Silver Card - Jones': 5750165,
    'Silver Card - Lufkin': 5750166,
    'Silver Card - Maeve': 5750167,
    'Silver Card - Montmorency': 5750168,
    'Silver Card - Mopsus': 5750169,
    'Silver Card - Nutcombe': 5750170,
    'Silver Card - Oglethorpe': 5750171,
    'Silver Card - Oldridge': 5750172,
    'Silver Card - Oliphant': 5750173,
    'Silver Card - Plunkett': 5750174,
    'Silver Card - Rastrick': 5750175,
    'Silver Card - Shimpling': 5750176,
    'Silver Card - Shingleton': 5750177,
    'Silver Card - Smethwyck': 5750178,
    'Silver Card - Stalk': 5750179,
    'Silver Card - Summerbee': 5750180,
    'Silver Card - Thurkell': 5750181,
    'Silver Card - Toothill': 5750182,
    'Silver Card - Tremlett': 5750183,
    'Silver Card - Tugwood': 5750184,
    'Silver Card - Wadcock': 5750185,
    'Silver Card - Wendelin': 5750186,
    'Silver Card - Wildsmith': 5750187,
    'Silver Card - Wright': 5750188,
    'Silver Card - Youdle': 5750189,
    'Gold Card - Bott': 5750190,
    'Gold Card - Dumbledore': 5750191,
    'Gold Card - Gryffindor': 5750192,
    'Gold Card - Herpo': 5750193,
    'Gold Card - Hufflepuff': 5750194,
    'Gold Card - Knightley': 5750195,
    'Gold Card - Paracelsus': 5750196,
    'Gold Card - Pinkstone': 5750197,
    'Gold Card - Potter': 5750198,
    'Gold Card - Ravenclaw': 5750199,
    'Gold Card - Slytherin': 5750200,
    'Small Pile of Beans': 5750300,
    'Medium Pile of Beans': 5750301,
    'Large Pile of Beans': 5750302,
    'Massive Pile of Beans': 5750303,
    'Wiggenweld Potion': 5750304,
    'Wiggentree Bark': 5750305,
    'Flobberworm Mucous': 5750306,
    'Chocolate Frog': 5750307,
}

ITEM_CLASSIFICATIONS: dict[str, ItemClassification] = {
    'Alohomora': ItemClassification.progression,
    'Diffindo': ItemClassification.progression,
    'Flipendo': ItemClassification.progression,
    'Lumos': ItemClassification.progression,
    'Rictusempra': ItemClassification.progression,
    'Skurge': ItemClassification.progression,
    'Spongify': ItemClassification.progression,
    'Chamber of Secrets Key': ItemClassification.progression,
    'Spongify Classroom Key': ItemClassification.progression,
    'Skurge Classroom Key': ItemClassification.progression,
    'Rictusempra Classroom Key': ItemClassification.progression,
    'Diffindo Classroom Key': ItemClassification.progression,
    'Boomslang Level Key': ItemClassification.progression,
    'Whomping Willow Key': ItemClassification.progression,
    'Forbidden Forest Key': ItemClassification.progression,
    'Slytherin Common Room Key': ItemClassification.progression,
    'Goyle Level Key': ItemClassification.progression,
    'Bicorn Level Key': ItemClassification.progression,
    'Duelling Club Key': ItemClassification.progression,
    'Quidditch Pitch Key': ItemClassification.progression,
    'Nimbus 2001': ItemClassification.useful,
    'Quidditch Armour': ItemClassification.useful,
    'Bronze Card - Agrippa': ItemClassification.useful,
    'Bronze Card - Alderton': ItemClassification.useful,
    'Bronze Card - Barbary': ItemClassification.useful,
    'Bronze Card - Barkwith': ItemClassification.useful,
    'Bronze Card - Belby': ItemClassification.useful,
    'Bronze Card - Blane': ItemClassification.useful,
    'Bronze Card - Bloxam': ItemClassification.useful,
    'Bronze Card - Bonham': ItemClassification.useful,
    'Bronze Card - Catchlove': ItemClassification.useful,
    'Bronze Card - Elphick': ItemClassification.useful,
    'Bronze Card - Ethelred': ItemClassification.useful,
    'Bronze Card - Fancourt': ItemClassification.useful,
    'Bronze Card - Goshawk': ItemClassification.useful,
    'Bronze Card - Graves': ItemClassification.useful,
    'Bronze Card - Gunhilda': ItemClassification.useful,
    'Bronze Card - Hipworth': ItemClassification.useful,
    'Bronze Card - Kegg': ItemClassification.useful,
    'Bronze Card - Ketteridge': ItemClassification.useful,
    'Bronze Card - Marjoribanks': ItemClassification.useful,
    'Bronze Card - Merlin': ItemClassification.useful,
    'Bronze Card - Merwyn': ItemClassification.useful,
    'Bronze Card - Muldoon': ItemClassification.useful,
    'Bronze Card - Ollerton': ItemClassification.useful,
    'Bronze Card - Peakes': ItemClassification.useful,
    'Bronze Card - Pilliwickle': ItemClassification.useful,
    'Bronze Card - Platt': ItemClassification.useful,
    'Bronze Card - Plumpton': ItemClassification.useful,
    'Bronze Card - Po': ItemClassification.useful,
    'Bronze Card - Pokeby': ItemClassification.useful,
    'Bronze Card - Sawbridge': ItemClassification.useful,
    'Bronze Card - Scamander': ItemClassification.useful,
    'Bronze Card - Starkey': ItemClassification.useful,
    'Bronze Card - Stroulger': ItemClassification.useful,
    'Bronze Card - Stump': ItemClassification.useful,
    'Bronze Card - Sweeting': ItemClassification.useful,
    'Bronze Card - Sykes': ItemClassification.useful,
    'Bronze Card - Thruston': ItemClassification.useful,
    'Bronze Card - Toke': ItemClassification.useful,
    'Bronze Card - Twonk': ItemClassification.useful,
    'Bronze Card - Ulric': ItemClassification.useful,
    'Bronze Card - Vablatsky': ItemClassification.useful,
    'Bronze Card - Waffling': ItemClassification.useful,
    'Bronze Card - Wagtail': ItemClassification.useful,
    'Bronze Card - Warbeck': ItemClassification.useful,
    'Bronze Card - Wellbeloved': ItemClassification.useful,
    'Bronze Card - Wenlock': ItemClassification.useful,
    'Bronze Card - Whitehorn': ItemClassification.useful,
    'Bronze Card - Wintringham': ItemClassification.useful,
    'Bronze Card - Withers': ItemClassification.useful,
    'Bronze Card - Woodcroft': ItemClassification.useful,
    'Silver Card - Andros': ItemClassification.progression_skip_balancing,
    'Silver Card - Beamish': ItemClassification.progression_skip_balancing,
    'Silver Card - Chittock': ItemClassification.progression_skip_balancing,
    'Silver Card - Circe': ItemClassification.progression_skip_balancing,
    'Silver Card - Clagg': ItemClassification.progression_skip_balancing,
    'Silver Card - Cliodne': ItemClassification.progression_skip_balancing,
    'Silver Card - Cronk': ItemClassification.progression_skip_balancing,
    'Silver Card - Crumb': ItemClassification.progression_skip_balancing,
    'Silver Card - Dodderidge': ItemClassification.progression_skip_balancing,
    'Silver Card - Duke': ItemClassification.progression_skip_balancing,
    'Silver Card - Fay': ItemClassification.progression_skip_balancing,
    'Silver Card - Fulbert': ItemClassification.progression_skip_balancing,
    'Silver Card - Furmage': ItemClassification.progression_skip_balancing,
    'Silver Card - Gregory': ItemClassification.progression_skip_balancing,
    'Silver Card - Grunnion': ItemClassification.progression_skip_balancing,
    'Silver Card - Jones': ItemClassification.progression_skip_balancing,
    'Silver Card - Lufkin': ItemClassification.progression_skip_balancing,
    'Silver Card - Maeve': ItemClassification.progression_skip_balancing,
    'Silver Card - Montmorency': ItemClassification.progression_skip_balancing,
    'Silver Card - Mopsus': ItemClassification.progression_skip_balancing,
    'Silver Card - Nutcombe': ItemClassification.progression_skip_balancing,
    'Silver Card - Oglethorpe': ItemClassification.progression_skip_balancing,
    'Silver Card - Oldridge': ItemClassification.progression_skip_balancing,
    'Silver Card - Oliphant': ItemClassification.progression_skip_balancing,
    'Silver Card - Plunkett': ItemClassification.progression_skip_balancing,
    'Silver Card - Rastrick': ItemClassification.progression_skip_balancing,
    'Silver Card - Shimpling': ItemClassification.progression_skip_balancing,
    'Silver Card - Shingleton': ItemClassification.progression_skip_balancing,
    'Silver Card - Smethwyck': ItemClassification.progression_skip_balancing,
    'Silver Card - Stalk': ItemClassification.progression_skip_balancing,
    'Silver Card - Summerbee': ItemClassification.progression_skip_balancing,
    'Silver Card - Thurkell': ItemClassification.progression_skip_balancing,
    'Silver Card - Toothill': ItemClassification.progression_skip_balancing,
    'Silver Card - Tremlett': ItemClassification.progression_skip_balancing,
    'Silver Card - Tugwood': ItemClassification.progression_skip_balancing,
    'Silver Card - Wadcock': ItemClassification.progression_skip_balancing,
    'Silver Card - Wendelin': ItemClassification.progression_skip_balancing,
    'Silver Card - Wildsmith': ItemClassification.progression_skip_balancing,
    'Silver Card - Wright': ItemClassification.progression_skip_balancing,
    'Silver Card - Youdle': ItemClassification.progression_skip_balancing,
    'Gold Card - Bott': ItemClassification.useful,
    'Gold Card - Dumbledore': ItemClassification.useful,
    'Gold Card - Gryffindor': ItemClassification.useful,
    'Gold Card - Herpo': ItemClassification.useful,
    'Gold Card - Hufflepuff': ItemClassification.useful,
    'Gold Card - Knightley': ItemClassification.useful,
    'Gold Card - Paracelsus': ItemClassification.useful,
    'Gold Card - Pinkstone': ItemClassification.useful,
    'Gold Card - Potter': ItemClassification.useful,
    'Gold Card - Ravenclaw': ItemClassification.useful,
    'Gold Card - Slytherin': ItemClassification.useful,
    'Small Pile of Beans': ItemClassification.filler,
    'Medium Pile of Beans': ItemClassification.filler,
    'Large Pile of Beans': ItemClassification.filler,
    'Massive Pile of Beans': ItemClassification.filler,
    'Wiggenweld Potion': ItemClassification.filler,
    'Wiggentree Bark': ItemClassification.filler,
    'Flobberworm Mucous': ItemClassification.filler,
    'Chocolate Frog': ItemClassification.filler,
}

ITEM_GROUPS: dict[str, list[str]] = {
    'Spells': ['Alohomora', 'Diffindo', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge', 'Spongify'],
    'Key Items': [],
    'Bingo Keys': ['Chamber of Secrets Key', 'Spongify Classroom Key', 'Skurge Classroom Key', 'Rictusempra Classroom Key', 'Diffindo Classroom Key', 'Boomslang Level Key', 'Whomping Willow Key', 'Forbidden Forest Key', 'Slytherin Common Room Key', 'Goyle Level Key', 'Bicorn Level Key', 'Duelling Club Key', 'Quidditch Pitch Key'],
    'Equipment': ['Nimbus 2001', 'Quidditch Armour'],
    'Cards (Bronze)': ['Bronze Card - Agrippa', 'Bronze Card - Alderton', 'Bronze Card - Barbary', 'Bronze Card - Barkwith', 'Bronze Card - Belby', 'Bronze Card - Blane', 'Bronze Card - Bloxam', 'Bronze Card - Bonham', 'Bronze Card - Catchlove', 'Bronze Card - Elphick', 'Bronze Card - Ethelred', 'Bronze Card - Fancourt', 'Bronze Card - Goshawk', 'Bronze Card - Graves', 'Bronze Card - Gunhilda', 'Bronze Card - Hipworth', 'Bronze Card - Kegg', 'Bronze Card - Ketteridge', 'Bronze Card - Marjoribanks', 'Bronze Card - Merlin', 'Bronze Card - Merwyn', 'Bronze Card - Muldoon', 'Bronze Card - Ollerton', 'Bronze Card - Peakes', 'Bronze Card - Pilliwickle', 'Bronze Card - Platt', 'Bronze Card - Plumpton', 'Bronze Card - Po', 'Bronze Card - Pokeby', 'Bronze Card - Sawbridge', 'Bronze Card - Scamander', 'Bronze Card - Starkey', 'Bronze Card - Stroulger', 'Bronze Card - Stump', 'Bronze Card - Sweeting', 'Bronze Card - Sykes', 'Bronze Card - Thruston', 'Bronze Card - Toke', 'Bronze Card - Twonk', 'Bronze Card - Ulric', 'Bronze Card - Vablatsky', 'Bronze Card - Waffling', 'Bronze Card - Wagtail', 'Bronze Card - Warbeck', 'Bronze Card - Wellbeloved', 'Bronze Card - Wenlock', 'Bronze Card - Whitehorn', 'Bronze Card - Wintringham', 'Bronze Card - Withers', 'Bronze Card - Woodcroft'],
    'Cards (Silver)': ['Silver Card - Andros', 'Silver Card - Beamish', 'Silver Card - Chittock', 'Silver Card - Circe', 'Silver Card - Clagg', 'Silver Card - Cliodne', 'Silver Card - Cronk', 'Silver Card - Crumb', 'Silver Card - Dodderidge', 'Silver Card - Duke', 'Silver Card - Fay', 'Silver Card - Fulbert', 'Silver Card - Furmage', 'Silver Card - Gregory', 'Silver Card - Grunnion', 'Silver Card - Jones', 'Silver Card - Lufkin', 'Silver Card - Maeve', 'Silver Card - Montmorency', 'Silver Card - Mopsus', 'Silver Card - Nutcombe', 'Silver Card - Oglethorpe', 'Silver Card - Oldridge', 'Silver Card - Oliphant', 'Silver Card - Plunkett', 'Silver Card - Rastrick', 'Silver Card - Shimpling', 'Silver Card - Shingleton', 'Silver Card - Smethwyck', 'Silver Card - Stalk', 'Silver Card - Summerbee', 'Silver Card - Thurkell', 'Silver Card - Toothill', 'Silver Card - Tremlett', 'Silver Card - Tugwood', 'Silver Card - Wadcock', 'Silver Card - Wendelin', 'Silver Card - Wildsmith', 'Silver Card - Wright', 'Silver Card - Youdle'],
    'Cards (Gold)': ['Gold Card - Bott', 'Gold Card - Dumbledore', 'Gold Card - Gryffindor', 'Gold Card - Herpo', 'Gold Card - Hufflepuff', 'Gold Card - Knightley', 'Gold Card - Paracelsus', 'Gold Card - Pinkstone', 'Gold Card - Potter', 'Gold Card - Ravenclaw', 'Gold Card - Slytherin'],
    'Filler': ['Small Pile of Beans', 'Medium Pile of Beans', 'Large Pile of Beans', 'Massive Pile of Beans', 'Wiggenweld Potion', 'Wiggentree Bark', 'Flobberworm Mucous', 'Chocolate Frog'],
}

FILLER_NAMES: list[str] = ['Small Pile of Beans', 'Medium Pile of Beans', 'Large Pile of Beans', 'Massive Pile of Beans', 'Wiggenweld Potion', 'Wiggentree Bark', 'Flobberworm Mucous', 'Chocolate Frog']

# Map UScript card class name → AP item display name. Used by the client
# when forwarding 'GRANT <classname>' messages to the mod for cards.
CARD_CLASS_TO_ITEM_NAME: dict[str, str] = {
    'WCAgrippa': 'Bronze Card - Agrippa',
    'WCAlderton': 'Bronze Card - Alderton',
    'WCBarbary': 'Bronze Card - Barbary',
    'WCBarkwith': 'Bronze Card - Barkwith',
    'WCBelby': 'Bronze Card - Belby',
    'WCBlane': 'Bronze Card - Blane',
    'WCBloxam': 'Bronze Card - Bloxam',
    'WCBonham': 'Bronze Card - Bonham',
    'WCCatchlove': 'Bronze Card - Catchlove',
    'WCElphick': 'Bronze Card - Elphick',
    'WCEthelred': 'Bronze Card - Ethelred',
    'WCFancourt': 'Bronze Card - Fancourt',
    'WCGoshawk': 'Bronze Card - Goshawk',
    'WCGraves': 'Bronze Card - Graves',
    'WCGunhilda': 'Bronze Card - Gunhilda',
    'WCHipworth': 'Bronze Card - Hipworth',
    'WCKegg': 'Bronze Card - Kegg',
    'WCKetteridge': 'Bronze Card - Ketteridge',
    'WCMarjoribanks': 'Bronze Card - Marjoribanks',
    'WCMerlin': 'Bronze Card - Merlin',
    'WCMerwyn': 'Bronze Card - Merwyn',
    'WCMuldoon': 'Bronze Card - Muldoon',
    'WCOllerton': 'Bronze Card - Ollerton',
    'WCPeakes': 'Bronze Card - Peakes',
    'WCPilliwickle': 'Bronze Card - Pilliwickle',
    'WCPlatt': 'Bronze Card - Platt',
    'WCPlumpton': 'Bronze Card - Plumpton',
    'WCPo': 'Bronze Card - Po',
    'WCPokeby': 'Bronze Card - Pokeby',
    'WCSawbridge': 'Bronze Card - Sawbridge',
    'WCScamander': 'Bronze Card - Scamander',
    'WCStarkey': 'Bronze Card - Starkey',
    'WCStroulger': 'Bronze Card - Stroulger',
    'WCStump': 'Bronze Card - Stump',
    'WCSweeting': 'Bronze Card - Sweeting',
    'WCSykes': 'Bronze Card - Sykes',
    'WCThruston': 'Bronze Card - Thruston',
    'WCToke': 'Bronze Card - Toke',
    'WCTwonk': 'Bronze Card - Twonk',
    'WCUlric': 'Bronze Card - Ulric',
    'WCVablatsky': 'Bronze Card - Vablatsky',
    'WCWaffling': 'Bronze Card - Waffling',
    'WCWagtail': 'Bronze Card - Wagtail',
    'WCWarbeck': 'Bronze Card - Warbeck',
    'WCWellbeloved': 'Bronze Card - Wellbeloved',
    'WCWenlock': 'Bronze Card - Wenlock',
    'WCWhitehorn': 'Bronze Card - Whitehorn',
    'WCWintringham': 'Bronze Card - Wintringham',
    'WCWithers': 'Bronze Card - Withers',
    'WCWoodcroft': 'Bronze Card - Woodcroft',
    'WCAndros': 'Silver Card - Andros',
    'WCBeamish': 'Silver Card - Beamish',
    'WCChittock': 'Silver Card - Chittock',
    'WCCirce': 'Silver Card - Circe',
    'WCClagg': 'Silver Card - Clagg',
    'WCCliodne': 'Silver Card - Cliodne',
    'WCCronk': 'Silver Card - Cronk',
    'WCCrumb': 'Silver Card - Crumb',
    'WCDodderidge': 'Silver Card - Dodderidge',
    'WCDuke': 'Silver Card - Duke',
    'WCFay': 'Silver Card - Fay',
    'WCFulbert': 'Silver Card - Fulbert',
    'WCFurmage': 'Silver Card - Furmage',
    'WCGregory': 'Silver Card - Gregory',
    'WCGrunnion': 'Silver Card - Grunnion',
    'WCJones': 'Silver Card - Jones',
    'WCLufkin': 'Silver Card - Lufkin',
    'WCMaeve': 'Silver Card - Maeve',
    'WCMontmorency': 'Silver Card - Montmorency',
    'WCMopsus': 'Silver Card - Mopsus',
    'WCNutcombe': 'Silver Card - Nutcombe',
    'WCOglethorpe': 'Silver Card - Oglethorpe',
    'WCOldridge': 'Silver Card - Oldridge',
    'WCOliphant': 'Silver Card - Oliphant',
    'WCPlunkett': 'Silver Card - Plunkett',
    'WCRastrick': 'Silver Card - Rastrick',
    'WCShimpling': 'Silver Card - Shimpling',
    'WCShingleton': 'Silver Card - Shingleton',
    'WCSmethwyck': 'Silver Card - Smethwyck',
    'WCStalk': 'Silver Card - Stalk',
    'WCSummerbee': 'Silver Card - Summerbee',
    'WCThurkell': 'Silver Card - Thurkell',
    'WCToothill': 'Silver Card - Toothill',
    'WCTremlett': 'Silver Card - Tremlett',
    'WCTugwood': 'Silver Card - Tugwood',
    'WCWadcock': 'Silver Card - Wadcock',
    'WCWendelin': 'Silver Card - Wendelin',
    'WCWildsmith': 'Silver Card - Wildsmith',
    'WCWright': 'Silver Card - Wright',
    'WCYoudle': 'Silver Card - Youdle',
    'WCBott': 'Gold Card - Bott',
    'WCDumbledore': 'Gold Card - Dumbledore',
    'WCGriffindor': 'Gold Card - Gryffindor',
    'WCHerpo': 'Gold Card - Herpo',
    'WCHufflepuff': 'Gold Card - Hufflepuff',
    'WCKnightley': 'Gold Card - Knightley',
    'WCParacelsus': 'Gold Card - Paracelsus',
    'WCPinkstone': 'Gold Card - Pinkstone',
    'WCPotter': 'Gold Card - Potter',
    'WCRavenclaw': 'Gold Card - Ravenclaw',
    'WCSlytherin': 'Gold Card - Slytherin',
}
