"""Auto-generated. Do not edit by hand; regenerate from data/locations.yaml."""

BASE_ID = 5760000

LOCATION_NAME_TO_ID: dict[str, int] = {
    'Learned Rictusempra': 5760001,
    'Learned Skurge': 5760002,
    'Learned Diffindo': 5760003,
    'Learned Spongify': 5760004,
    'Bicorn Level - Card Agrippa': 5760100,
    'Entry Hall - Card Alderton': 5760101,
    'Rictusempra Challenge - Card Barbary': 5760102,
    'Grand Staircase - Card Barkwith': 5760103,
    'Skurge Challenge - Card Belby': 5760104,
    'Grand Staircase - Card Blane': 5760105,
    'Goyle Level - Card Bloxam': 5760106,
    'Grand Staircase - Card Bonham': 5760107,
    'Skurge Challenge - Card Catchlove': 5760108,
    'Chamber of Secrets - Card Elphick': 5760109,
    'Grand Staircase - Card Ethelred': 5760110,
    'Forbidden Forest - Card Fancourt': 5760111,
    'Bicorn Level - Card Goshawk': 5760112,
    'Rictusempra Challenge - Card Graves': 5760113,
    'Entry Hall - Card Gunhilda': 5760114,
    'Grand Staircase - Card Hipworth': 5760115,
    'Skurge Challenge - Card Kegg': 5760116,
    'Diffindo Challenge - Card Ketteridge': 5760117,
    'Castle Exterior - Card Marjoribanks': 5760118,
    'Spongify Challenge - Card Merlin': 5760119,
    'Diffindo Challenge - Card Merwyn': 5760120,
    "Dumbledore's Study - Card Muldoon": 5760121,
    'Forbidden Forest - Card Ollerton': 5760122,
    'Bicorn Level - Card Peakes': 5760123,
    'Slytherin Common Room - Card Pilliwickle': 5760124,
    'Slytherin Common Room - Card Platt': 5760125,
    'Goyle Level - Card Plumpton': 5760126,
    'Spongify Challenge - Card Po': 5760127,
    'Castle Exterior - Card Pokeby': 5760128,
    'Entry Hall - Card Sawbridge': 5760129,
    'Forbidden Forest - Card Scamander': 5760130,
    'Whomping Willow - Card Starkey': 5760131,
    'Goyle Level - Card Stroulger': 5760132,
    'Bicorn Level - Card Stump': 5760133,
    'Castle Exterior - Card Sweeting': 5760134,
    'Castle Exterior - Card Sykes': 5760135,
    'Rictusempra Challenge - Card Thruston': 5760136,
    'Boomslang Level - Card Toke': 5760137,
    'Castle Exterior - Card Twonk': 5760138,
    'Diffindo Challenge - Card Ulric': 5760139,
    'Grand Staircase - Card Vablatsky': 5760140,
    'Slytherin Common Room - Card Waffling': 5760141,
    'Rictusempra Challenge - Card Wagtail': 5760142,
    'Spongify Challenge - Card Warbeck': 5760143,
    'Forbidden Forest - Card Wellbeloved': 5760144,
    'Skurge Challenge - Card Wenlock': 5760145,
    'Goyle Level - Card Whitehorn': 5760146,
    'Rictusempra Challenge - Card Wintringham': 5760147,
    'Diffindo Challenge - Card Withers': 5760148,
    'Spongify Challenge - Card Woodcroft': 5760149,
    'Entry Hall - Card Andros': 5760150,
    "Dumbledore's Study - Card Beamish": 5760151,
    'Rictusempra Challenge - Card Chittock': 5760152,
    'Goyle Level - Card Circe': 5760153,
    'Slytherin Common Room - Card Clagg': 5760154,
    'Forbidden Forest - Card Cliodne': 5760155,
    'Bicorn Level - Card Cronk': 5760156,
    'Rictusempra Challenge - Card Crumb': 5760157,
    'Entry Hall - Card Dodderidge': 5760158,
    'Rictusempra Challenge - Card Duke': 5760159,
    'Slytherin Common Room - Card Fay': 5760160,
    'Skurge Challenge - Card Fulbert': 5760161,
    'Spongify Challenge - Card Furmage': 5760162,
    'Skurge Challenge - Card Gregory': 5760163,
    'Spongify Challenge - Card Grunnion': 5760164,
    'Entry Hall - Card Jones': 5760165,
    'Grand Staircase - Card Lufkin': 5760166,
    'Grand Staircase - Card Maeve': 5760167,
    'Entry Hall - Card Montmorency': 5760168,
    'Entry Hall - Card Mopsus': 5760169,
    'Bicorn Level - Card Nutcombe': 5760170,
    'Castle Exterior - Card Oglethorpe': 5760171,
    'Grand Staircase - Card Oldridge': 5760172,
    'Forbidden Forest - Card Oliphant': 5760173,
    'Castle Exterior - Card Plunkett': 5760174,
    'Spongify Challenge - Card Rastrick': 5760175,
    'Diffindo Challenge - Card Shimpling': 5760176,
    'Entry Hall - Card Shingleton': 5760177,
    'Diffindo Challenge - Card Smethwyck': 5760178,
    'Diffindo Challenge - Card Stalk': 5760179,
    'Spongify Challenge - Card Summerbee': 5760180,
    'Diffindo Challenge - Card Thurkell': 5760181,
    'Grand Staircase - Card Toothill': 5760182,
    'Rictusempra Challenge - Card Tremlett': 5760183,
    'Boomslang Level - Card Tugwood': 5760184,
    'Castle Exterior - Card Wadcock': 5760185,
    'Entry Hall - Card Wendelin': 5760186,
    'Goyle Level - Card Wildsmith': 5760187,
    'Entry Hall - Card Wright': 5760188,
    'Castle Exterior - Card Youdle': 5760189,
    'Gold Card Room - Card Bott': 5760190,
    'Gold Card Room - Card Dumbledore': 5760191,
    'Gold Card Room - Card Gryffindor': 5760192,
    'Gold Card Room - Card Herpo': 5760193,
    'Gold Card Room - Card Hufflepuff': 5760194,
    'Gold Card Room - Card Knightley': 5760195,
    'Gold Card Room - Card Paracelsus': 5760196,
    'Gold Card Room - Card Pinkstone': 5760197,
    'Gold Card Room - Card Potter': 5760198,
    'Gold Card Room - Card Ravenclaw': 5760199,
    'Gold Card Room - Card Slytherin': 5760200,
    'Castle Exterior - Nimbus 2001': 5760005,
    'Castle Exterior - Quidditch Armour': 5760006,
    'Duelling Club - Duel Rank 1': 5760600,
    'Duelling Club - Duel Rank 2': 5760601,
    'Duelling Club - Duel Rank 3': 5760602,
    'Duelling Club - Duel Rank 4': 5760603,
    'Duelling Club - Duel Rank 5': 5760604,
    'Duelling Club - Duel Rank 6': 5760605,
    'Duelling Club - Duel Rank 7': 5760606,
    'Duelling Club - Duel Rank 8': 5760607,
    'Duelling Club - Duel Rank 9': 5760608,
    'Duelling Club - Duel Rank 10': 5760609,
    'Quidditch - Match 1 (Hufflepuff)': 5760620,
    'Quidditch - Match 2 (Ravenclaw)': 5760621,
    'Quidditch - Match 3 (Slytherin)': 5760622,
    'Quidditch - Match 4 (Hufflepuff)': 5760623,
    'Quidditch - Match 5 (Ravenclaw)': 5760624,
    'Quidditch - Match 6 (Slytherin)': 5760625,
    'Rictusempra Challenge - Beat Par Time': 5760630,
    'Skurge Challenge - Beat Par Time': 5760631,
    'Diffindo Challenge - Beat Par Time': 5760632,
    'Spongify Challenge - Beat Par Time': 5760633,
    'Bicorn Level - Secret 2': 5760300,
    'Bicorn Level - Secret 1': 5760301,
    'Bicorn Level - Secret 6': 5760302,
    'Bicorn Level - Secret 3': 5760303,
    'Bicorn Level - Secret 4': 5760304,
    'Bicorn Level - Secret 5': 5760305,
    'Bicorn Level - Secret 7': 5760306,
    'Boomslang Level - Secret 3': 5760307,
    'Boomslang Level - Secret 2': 5760308,
    'Boomslang Level - Secret 1': 5760309,
    'Castle Exterior - Secret 1': 5760310,
    'Castle Exterior - Secret 2': 5760311,
    'Castle Exterior - Secret 3': 5760312,
    'Castle Exterior - Secret 4': 5760313,
    'Castle Exterior - Secret 5': 5760314,
    'Castle Exterior - Secret 6': 5760315,
    'Castle Exterior - Secret 7': 5760316,
    'Castle Exterior - Secret 8': 5760317,
    'Chamber of Secrets - Secret 3': 5760318,
    'Chamber of Secrets - Secret 2': 5760319,
    'Chamber of Secrets - Secret 1': 5760320,
    'Chamber of Secrets - Secret 5': 5760322,
    'Chamber of Secrets - Secret 4': 5760323,
    'Chamber of Secrets - Secret 6': 5760324,
    "Dumbledore's Study - Secret": 5760362,
    'Diffindo Challenge - Secret 1': 5760325,
    'Diffindo Challenge - Secret 2': 5760326,
    'Diffindo Challenge - Secret 3': 5760327,
    'Diffindo Challenge - Secret 5': 5760328,
    'Diffindo Challenge - Secret 6': 5760329,
    'Diffindo Challenge - Secret 4': 5760330,
    'Diffindo Challenge - Secret 7': 5760331,
    'Diffindo Challenge - Secret 8': 5760332,
    'Diffindo Challenge - Secret 9': 5760333,
    'Diffindo Challenge - Secret 10': 5760334,
    'Diffindo Challenge - Secret 11': 5760335,
    'Forbidden Forest - Secret 4': 5760336,
    'Forbidden Forest - Secret 3': 5760337,
    'Forbidden Forest - Secret 2': 5760338,
    'Forbidden Forest - Secret 1': 5760339,
    'Goyle Level - Secret 5': 5760340,
    'Goyle Level - Secret 6': 5760341,
    'Goyle Level - Secret 8': 5760342,
    'Goyle Level - Secret 7': 5760343,
    'Goyle Level - Secret 1': 5760344,
    'Goyle Level - Secret 3': 5760345,
    'Goyle Level - Secret 4': 5760346,
    'Goyle Level - Secret 2': 5760347,
    'Entry Hall - Secret 1': 5760348,
    'Entry Hall - Secret 2': 5760349,
    'Entry Hall - Secret 3': 5760350,
    'Entry Hall - Secret 4': 5760351,
    'Entry Hall - Secret 5': 5760352,
    'Entry Hall - Secret 6': 5760353,
    'Entry Hall - Secret 7': 5760354,
    'Entry Hall - Secret 8': 5760355,
    'Entry Hall - Secret 9': 5760356,
    'Entry Hall - Secret 10': 5760357,
    'Entry Hall - Secret 11': 5760358,
    'Entry Hall - Secret 12': 5760359,
    'Grand Staircase - Secret 1': 5760360,
    'Grand Staircase - Secret 2': 5760361,
    'Grand Staircase - Secret 3': 5760363,
    'Grand Staircase - Secret 4': 5760364,
    'Grand Staircase - Secret 5': 5760365,
    'Grand Staircase - Secret 6': 5760366,
    'Grand Staircase - Secret 7': 5760367,
    'Grand Staircase - Secret 8': 5760368,
    'Grand Staircase - Secret 9': 5760369,
    'Rictusempra Challenge - Secret 1': 5760370,
    'Rictusempra Challenge - Secret 3': 5760371,
    'Rictusempra Challenge - Secret 5': 5760372,
    'Rictusempra Challenge - Secret 4': 5760373,
    'Rictusempra Challenge - Secret 6': 5760374,
    'Rictusempra Challenge - Secret 7': 5760375,
    'Rictusempra Challenge - Secret 2': 5760376,
    'Skurge Challenge - Secret 1': 5760377,
    'Skurge Challenge - Secret 2': 5760378,
    'Skurge Challenge - Secret 3': 5760379,
    'Skurge Challenge - Secret 4': 5760380,
    'Skurge Challenge - Secret 5': 5760381,
    'Skurge Challenge - Secret 6': 5760382,
    'Skurge Challenge - Secret 7': 5760383,
    'Slytherin Common Room - Secret 7': 5760384,
    'Slytherin Common Room - Secret 6': 5760385,
    'Slytherin Common Room - Secret 5': 5760386,
    'Slytherin Common Room - Secret 8': 5760387,
    'Slytherin Common Room - Secret 4': 5760388,
    'Slytherin Common Room - Secret 3': 5760389,
    'Slytherin Common Room - Secret 2': 5760390,
    'Slytherin Common Room - Secret 1': 5760391,
    'Spongify Challenge - Secret 1': 5760392,
    'Spongify Challenge - Secret 2': 5760393,
    'Spongify Challenge - Secret 3': 5760394,
    'Spongify Challenge - Secret 4': 5760395,
    'Spongify Challenge - Secret 5': 5760396,
    'Spongify Challenge - Secret 6': 5760397,
    'Spongify Challenge - Secret 7': 5760398,
    'Spongify Challenge - Secret 8': 5760399,
    'Spongify Challenge - Secret 9': 5760400,
    'Spongify Challenge - Secret 10': 5760401,
    'Spongify Challenge - Secret 11': 5760402,
    'Spongify Challenge - Secret 12': 5760403,
    'Spongify Challenge - Secret 13': 5760404,
    'Spongify Challenge - Secret 14': 5760405,
    'Spongify Challenge - Secret 15': 5760406,
    'Spongify Challenge - Secret 16': 5760407,
    'Whomping Willow - Secret 1': 5760408,
    'Whomping Willow - Secret 2': 5760409,
    'Gryffindor Challenge - Secret 1': 5760410,
    'Gryffindor Challenge - Secret 2': 5760411,
    'Gryffindor Challenge - Secret 3': 5760412,
    'Gryffindor Challenge - Secret 4': 5760413,
    'Gryffindor Challenge - Secret 5': 5760414,
    'Gryffindor Challenge - Secret 6': 5760415,
    'Gryffindor Challenge - Secret 7': 5760416,
    'Gryffindor Challenge - Secret 8': 5760417,
    'Gryffindor Challenge - Secret 9': 5760418,
    'Rictusempra Challenge - Challenge Star 3': 5760500,
    'Rictusempra Challenge - Challenge Star 10': 5760501,
    'Rictusempra Challenge - Challenge Star 2': 5760502,
    'Rictusempra Challenge - Challenge Star 6': 5760503,
    'Rictusempra Challenge - Challenge Star 1': 5760504,
    'Rictusempra Challenge - Challenge Star 4': 5760505,
    'Rictusempra Challenge - Challenge Star 8': 5760506,
    'Rictusempra Challenge - Challenge Star 5': 5760507,
    'Rictusempra Challenge - Challenge Star 7': 5760508,
    'Rictusempra Challenge - Challenge Star 9': 5760509,
    'Skurge Challenge - Challenge Star 1': 5760510,
    'Skurge Challenge - Challenge Star 2': 5760511,
    'Skurge Challenge - Challenge Star 3': 5760512,
    'Skurge Challenge - Challenge Star 4': 5760513,
    'Skurge Challenge - Challenge Star 5': 5760514,
    'Skurge Challenge - Challenge Star 6': 5760515,
    'Skurge Challenge - Challenge Star 7': 5760516,
    'Skurge Challenge - Challenge Star 10': 5760517,
    'Skurge Challenge - Challenge Star 9': 5760518,
    'Skurge Challenge - Challenge Star 8': 5760519,
    'Diffindo Challenge - Challenge Star 8': 5760520,
    'Diffindo Challenge - Challenge Star 14': 5760521,
    'Diffindo Challenge - Challenge Star 9': 5760522,
    'Diffindo Challenge - Challenge Star 12': 5760523,
    'Diffindo Challenge - Challenge Star 2': 5760524,
    'Diffindo Challenge - Challenge Star 4': 5760525,
    'Diffindo Challenge - Challenge Star 5': 5760526,
    'Diffindo Challenge - Challenge Star 6': 5760527,
    'Diffindo Challenge - Challenge Star 11': 5760528,
    'Diffindo Challenge - Challenge Star 10': 5760529,
    'Diffindo Challenge - Challenge Star 3': 5760530,
    'Diffindo Challenge - Challenge Star 7': 5760531,
    'Diffindo Challenge - Challenge Star 13': 5760532,
    'Diffindo Challenge - Challenge Star 1': 5760533,
    'Spongify Challenge - Challenge Star 1': 5760534,
    'Spongify Challenge - Challenge Star 3': 5760535,
    'Spongify Challenge - Challenge Star 2': 5760536,
    'Spongify Challenge - Challenge Star 4': 5760537,
    'Spongify Challenge - Challenge Star 5': 5760538,
    'Spongify Challenge - Challenge Star 6': 5760539,
    'Spongify Challenge - Challenge Star 7': 5760540,
    'Spongify Challenge - Challenge Star 8': 5760541,
    'Spongify Challenge - Challenge Star 9': 5760542,
    'Spongify Challenge - Challenge Star 10': 5760543,
    'Gryffindor Challenge - Challenge Star 7': 5760544,
    'Gryffindor Challenge - Challenge Star 8': 5760545,
    'Gryffindor Challenge - Challenge Star 9': 5760546,
    'Gryffindor Challenge - Challenge Star 1': 5760547,
    'Gryffindor Challenge - Challenge Star 2': 5760548,
    'Gryffindor Challenge - Challenge Star 3': 5760549,
    'Gryffindor Challenge - Challenge Star 6': 5760550,
    'Gryffindor Challenge - Challenge Star 4': 5760551,
    'Gryffindor Challenge - Challenge Star 5': 5760552,
    'Gryffindor Challenge - Challenge Star 10': 5760553,
    'Boomslang Level - Complete': 5760700,
    'Bicorn Level - Complete': 5760701,
    'Goyle Level - Complete': 5760702,
    'Forbidden Forest - Complete': 5760703,
    'Chamber of Secrets - Complete': 5760704,
    'Whomping Willow - Complete': 5760705,
    'Slytherin Common Room - Complete': 5760706,
    'Rictusempra Challenge - Complete': 5760707,
    'Skurge Challenge - Complete': 5760708,
    'Diffindo Challenge - Complete': 5760709,
    'Spongify Challenge - Complete': 5760710,
    'Gryffindor Challenge - Complete': 5760711,
    'Entry Hall - Card Vendor 1': 5760800,
    'Entry Hall - Card Vendor 2': 5760801,
    'Entry Hall - Card Vendor 3': 5760802,
    'Entry Hall - Ingredient Vendor 1': 5760803,
    'Entry Hall - Ingredient Vendor 2': 5760804,
    'Entry Hall - Ingredient Vendor 3': 5760805,
    'Grand Staircase - Card Vendor 1': 5760806,
    'Grand Staircase - Card Vendor 2': 5760807,
    'Grand Staircase - Ingredient Vendor 1': 5760808,
    'Castle Exterior - Card Vendor 1': 5760809,
    'Castle Exterior - Card Vendor 2': 5760810,
    'Castle Exterior - Ingredient Vendor 1': 5760811,
    'Castle Exterior - Ingredient Vendor 2': 5760812,
}

LOCATION_REGIONS: dict[str, str] = {
    'Learned Rictusempra': 'GrandStaircase',
    'Learned Skurge': 'GrandStaircase',
    'Learned Diffindo': 'CastleExterior',
    'Learned Spongify': 'GrandStaircase',
    'Bicorn Level - Card Agrippa': 'BicornLevel',
    'Entry Hall - Card Alderton': 'EntryHall',
    'Rictusempra Challenge - Card Barbary': 'RictusempraChallenge',
    'Grand Staircase - Card Barkwith': 'GrandStaircase',
    'Skurge Challenge - Card Belby': 'SkurgeChallenge',
    'Grand Staircase - Card Blane': 'GrandStaircase',
    'Goyle Level - Card Bloxam': 'GoyleLevel',
    'Grand Staircase - Card Bonham': 'GrandStaircase',
    'Skurge Challenge - Card Catchlove': 'SkurgeChallenge',
    'Chamber of Secrets - Card Elphick': 'ChamberOfSecrets',
    'Grand Staircase - Card Ethelred': 'GrandStaircase',
    'Forbidden Forest - Card Fancourt': 'ForbiddenForest',
    'Bicorn Level - Card Goshawk': 'BicornLevel',
    'Rictusempra Challenge - Card Graves': 'RictusempraChallenge',
    'Entry Hall - Card Gunhilda': 'EntryHall',
    'Grand Staircase - Card Hipworth': 'GrandStaircase',
    'Skurge Challenge - Card Kegg': 'SkurgeChallenge',
    'Diffindo Challenge - Card Ketteridge': 'DiffindoChallenge',
    'Castle Exterior - Card Marjoribanks': 'CastleExterior',
    'Spongify Challenge - Card Merlin': 'SpongifyChallenge',
    'Diffindo Challenge - Card Merwyn': 'DiffindoChallenge',
    "Dumbledore's Study - Card Muldoon": 'DumbledoreStudy',
    'Forbidden Forest - Card Ollerton': 'ForbiddenForest',
    'Bicorn Level - Card Peakes': 'BicornLevel',
    'Slytherin Common Room - Card Pilliwickle': 'SlytherinCommon',
    'Slytherin Common Room - Card Platt': 'SlytherinCommon',
    'Goyle Level - Card Plumpton': 'GoyleLevel',
    'Spongify Challenge - Card Po': 'SpongifyChallenge',
    'Castle Exterior - Card Pokeby': 'CastleExterior',
    'Entry Hall - Card Sawbridge': 'EntryHall',
    'Forbidden Forest - Card Scamander': 'ForbiddenForest',
    'Whomping Willow - Card Starkey': 'WhompingWillow',
    'Goyle Level - Card Stroulger': 'GoyleLevel',
    'Bicorn Level - Card Stump': 'BicornLevel',
    'Castle Exterior - Card Sweeting': 'CastleExterior',
    'Castle Exterior - Card Sykes': 'CastleExterior',
    'Rictusempra Challenge - Card Thruston': 'RictusempraChallenge',
    'Boomslang Level - Card Toke': 'BoomslangLevel',
    'Castle Exterior - Card Twonk': 'CastleExterior',
    'Diffindo Challenge - Card Ulric': 'DiffindoChallenge',
    'Grand Staircase - Card Vablatsky': 'GrandStaircase',
    'Slytherin Common Room - Card Waffling': 'SlytherinCommon',
    'Rictusempra Challenge - Card Wagtail': 'RictusempraChallenge',
    'Spongify Challenge - Card Warbeck': 'SpongifyChallenge',
    'Forbidden Forest - Card Wellbeloved': 'ForbiddenForest',
    'Skurge Challenge - Card Wenlock': 'SkurgeChallenge',
    'Goyle Level - Card Whitehorn': 'GoyleLevel',
    'Rictusempra Challenge - Card Wintringham': 'RictusempraChallenge',
    'Diffindo Challenge - Card Withers': 'DiffindoChallenge',
    'Spongify Challenge - Card Woodcroft': 'SpongifyChallenge',
    'Entry Hall - Card Andros': 'EntryHall',
    "Dumbledore's Study - Card Beamish": 'DumbledoreStudy',
    'Rictusempra Challenge - Card Chittock': 'RictusempraChallenge',
    'Goyle Level - Card Circe': 'GoyleLevel',
    'Slytherin Common Room - Card Clagg': 'SlytherinCommon',
    'Forbidden Forest - Card Cliodne': 'ForbiddenForest',
    'Bicorn Level - Card Cronk': 'BicornLevel',
    'Rictusempra Challenge - Card Crumb': 'RictusempraChallenge',
    'Entry Hall - Card Dodderidge': 'EntryHall',
    'Rictusempra Challenge - Card Duke': 'RictusempraChallenge',
    'Slytherin Common Room - Card Fay': 'SlytherinCommon',
    'Skurge Challenge - Card Fulbert': 'SkurgeChallenge',
    'Spongify Challenge - Card Furmage': 'SpongifyChallenge',
    'Skurge Challenge - Card Gregory': 'SkurgeChallenge',
    'Spongify Challenge - Card Grunnion': 'SpongifyChallenge',
    'Entry Hall - Card Jones': 'EntryHall',
    'Grand Staircase - Card Lufkin': 'GrandStaircase',
    'Grand Staircase - Card Maeve': 'GrandStaircase',
    'Entry Hall - Card Montmorency': 'EntryHall',
    'Entry Hall - Card Mopsus': 'EntryHall',
    'Bicorn Level - Card Nutcombe': 'BicornLevel',
    'Castle Exterior - Card Oglethorpe': 'CastleExterior',
    'Grand Staircase - Card Oldridge': 'GrandStaircase',
    'Forbidden Forest - Card Oliphant': 'ForbiddenForest',
    'Castle Exterior - Card Plunkett': 'CastleExterior',
    'Spongify Challenge - Card Rastrick': 'SpongifyChallenge',
    'Diffindo Challenge - Card Shimpling': 'DiffindoChallenge',
    'Entry Hall - Card Shingleton': 'EntryHall',
    'Diffindo Challenge - Card Smethwyck': 'DiffindoChallenge',
    'Diffindo Challenge - Card Stalk': 'DiffindoChallenge',
    'Spongify Challenge - Card Summerbee': 'SpongifyChallenge',
    'Diffindo Challenge - Card Thurkell': 'DiffindoChallenge',
    'Grand Staircase - Card Toothill': 'GrandStaircase',
    'Rictusempra Challenge - Card Tremlett': 'RictusempraChallenge',
    'Boomslang Level - Card Tugwood': 'BoomslangLevel',
    'Castle Exterior - Card Wadcock': 'CastleExterior',
    'Entry Hall - Card Wendelin': 'EntryHall',
    'Goyle Level - Card Wildsmith': 'GoyleLevel',
    'Entry Hall - Card Wright': 'EntryHall',
    'Castle Exterior - Card Youdle': 'CastleExterior',
    'Gold Card Room - Card Bott': 'GoldCardRoom',
    'Gold Card Room - Card Dumbledore': 'GoldCardRoom',
    'Gold Card Room - Card Gryffindor': 'GoldCardRoom',
    'Gold Card Room - Card Herpo': 'GoldCardRoom',
    'Gold Card Room - Card Hufflepuff': 'GoldCardRoom',
    'Gold Card Room - Card Knightley': 'GoldCardRoom',
    'Gold Card Room - Card Paracelsus': 'GoldCardRoom',
    'Gold Card Room - Card Pinkstone': 'GoldCardRoom',
    'Gold Card Room - Card Potter': 'GoldCardRoom',
    'Gold Card Room - Card Ravenclaw': 'GoldCardRoom',
    'Gold Card Room - Card Slytherin': 'GoldCardRoom',
    'Castle Exterior - Nimbus 2001': 'CastleExterior',
    'Castle Exterior - Quidditch Armour': 'CastleExterior',
    'Duelling Club - Duel Rank 1': 'DuellingClub',
    'Duelling Club - Duel Rank 2': 'DuellingClub',
    'Duelling Club - Duel Rank 3': 'DuellingClub',
    'Duelling Club - Duel Rank 4': 'DuellingClub',
    'Duelling Club - Duel Rank 5': 'DuellingClub',
    'Duelling Club - Duel Rank 6': 'DuellingClub',
    'Duelling Club - Duel Rank 7': 'DuellingClub',
    'Duelling Club - Duel Rank 8': 'DuellingClub',
    'Duelling Club - Duel Rank 9': 'DuellingClub',
    'Duelling Club - Duel Rank 10': 'DuellingClub',
    'Quidditch - Match 1 (Hufflepuff)': 'Quidditch',
    'Quidditch - Match 2 (Ravenclaw)': 'Quidditch',
    'Quidditch - Match 3 (Slytherin)': 'Quidditch',
    'Quidditch - Match 4 (Hufflepuff)': 'Quidditch',
    'Quidditch - Match 5 (Ravenclaw)': 'Quidditch',
    'Quidditch - Match 6 (Slytherin)': 'Quidditch',
    'Rictusempra Challenge - Beat Par Time': 'RictusempraChallenge',
    'Skurge Challenge - Beat Par Time': 'SkurgeChallenge',
    'Diffindo Challenge - Beat Par Time': 'DiffindoChallenge',
    'Spongify Challenge - Beat Par Time': 'SpongifyChallenge',
    'Bicorn Level - Secret 2': 'BicornLevel',
    'Bicorn Level - Secret 1': 'BicornLevel',
    'Bicorn Level - Secret 6': 'BicornLevel',
    'Bicorn Level - Secret 3': 'BicornLevel',
    'Bicorn Level - Secret 4': 'BicornLevel',
    'Bicorn Level - Secret 5': 'BicornLevel',
    'Bicorn Level - Secret 7': 'BicornLevel',
    'Boomslang Level - Secret 3': 'BoomslangLevel',
    'Boomslang Level - Secret 2': 'BoomslangLevel',
    'Boomslang Level - Secret 1': 'BoomslangLevel',
    'Castle Exterior - Secret 1': 'CastleExterior',
    'Castle Exterior - Secret 2': 'CastleExterior',
    'Castle Exterior - Secret 3': 'CastleExterior',
    'Castle Exterior - Secret 4': 'CastleExterior',
    'Castle Exterior - Secret 5': 'CastleExterior',
    'Castle Exterior - Secret 6': 'CastleExterior',
    'Castle Exterior - Secret 7': 'CastleExterior',
    'Castle Exterior - Secret 8': 'CastleExterior',
    'Chamber of Secrets - Secret 3': 'ChamberOfSecrets',
    'Chamber of Secrets - Secret 2': 'ChamberOfSecrets',
    'Chamber of Secrets - Secret 1': 'ChamberOfSecrets',
    'Chamber of Secrets - Secret 5': 'ChamberOfSecrets',
    'Chamber of Secrets - Secret 4': 'ChamberOfSecrets',
    'Chamber of Secrets - Secret 6': 'ChamberOfSecrets',
    "Dumbledore's Study - Secret": 'DumbledoreStudy',
    'Diffindo Challenge - Secret 1': 'DiffindoChallenge',
    'Diffindo Challenge - Secret 2': 'DiffindoChallenge',
    'Diffindo Challenge - Secret 3': 'DiffindoChallenge',
    'Diffindo Challenge - Secret 5': 'DiffindoChallenge',
    'Diffindo Challenge - Secret 6': 'DiffindoChallenge',
    'Diffindo Challenge - Secret 4': 'DiffindoChallenge',
    'Diffindo Challenge - Secret 7': 'DiffindoChallenge',
    'Diffindo Challenge - Secret 8': 'DiffindoChallenge',
    'Diffindo Challenge - Secret 9': 'DiffindoChallenge',
    'Diffindo Challenge - Secret 10': 'DiffindoChallenge',
    'Diffindo Challenge - Secret 11': 'DiffindoChallenge',
    'Forbidden Forest - Secret 4': 'ForbiddenForest',
    'Forbidden Forest - Secret 3': 'ForbiddenForest',
    'Forbidden Forest - Secret 2': 'ForbiddenForest',
    'Forbidden Forest - Secret 1': 'ForbiddenForest',
    'Goyle Level - Secret 5': 'GoyleLevel',
    'Goyle Level - Secret 6': 'GoyleLevel',
    'Goyle Level - Secret 8': 'GoyleLevel',
    'Goyle Level - Secret 7': 'GoyleLevel',
    'Goyle Level - Secret 1': 'GoyleLevel',
    'Goyle Level - Secret 3': 'GoyleLevel',
    'Goyle Level - Secret 4': 'GoyleLevel',
    'Goyle Level - Secret 2': 'GoyleLevel',
    'Entry Hall - Secret 1': 'EntryHall',
    'Entry Hall - Secret 2': 'EntryHall',
    'Entry Hall - Secret 3': 'EntryHall',
    'Entry Hall - Secret 4': 'EntryHall',
    'Entry Hall - Secret 5': 'EntryHall',
    'Entry Hall - Secret 6': 'EntryHall',
    'Entry Hall - Secret 7': 'EntryHall',
    'Entry Hall - Secret 8': 'EntryHall',
    'Entry Hall - Secret 9': 'EntryHall',
    'Entry Hall - Secret 10': 'EntryHall',
    'Entry Hall - Secret 11': 'EntryHall',
    'Entry Hall - Secret 12': 'EntryHall',
    'Grand Staircase - Secret 1': 'GrandStaircase',
    'Grand Staircase - Secret 2': 'GrandStaircase',
    'Grand Staircase - Secret 3': 'GrandStaircase',
    'Grand Staircase - Secret 4': 'GrandStaircase',
    'Grand Staircase - Secret 5': 'GrandStaircase',
    'Grand Staircase - Secret 6': 'GrandStaircase',
    'Grand Staircase - Secret 7': 'GrandStaircase',
    'Grand Staircase - Secret 8': 'GrandStaircase',
    'Grand Staircase - Secret 9': 'GrandStaircase',
    'Rictusempra Challenge - Secret 1': 'RictusempraChallenge',
    'Rictusempra Challenge - Secret 3': 'RictusempraChallenge',
    'Rictusempra Challenge - Secret 5': 'RictusempraChallenge',
    'Rictusempra Challenge - Secret 4': 'RictusempraChallenge',
    'Rictusempra Challenge - Secret 6': 'RictusempraChallenge',
    'Rictusempra Challenge - Secret 7': 'RictusempraChallenge',
    'Rictusempra Challenge - Secret 2': 'RictusempraChallenge',
    'Skurge Challenge - Secret 1': 'SkurgeChallenge',
    'Skurge Challenge - Secret 2': 'SkurgeChallenge',
    'Skurge Challenge - Secret 3': 'SkurgeChallenge',
    'Skurge Challenge - Secret 4': 'SkurgeChallenge',
    'Skurge Challenge - Secret 5': 'SkurgeChallenge',
    'Skurge Challenge - Secret 6': 'SkurgeChallenge',
    'Skurge Challenge - Secret 7': 'SkurgeChallenge',
    'Slytherin Common Room - Secret 7': 'SlytherinCommon',
    'Slytherin Common Room - Secret 6': 'SlytherinCommon',
    'Slytherin Common Room - Secret 5': 'SlytherinCommon',
    'Slytherin Common Room - Secret 8': 'SlytherinCommon',
    'Slytherin Common Room - Secret 4': 'SlytherinCommon',
    'Slytherin Common Room - Secret 3': 'SlytherinCommon',
    'Slytherin Common Room - Secret 2': 'SlytherinCommon',
    'Slytherin Common Room - Secret 1': 'SlytherinCommon',
    'Spongify Challenge - Secret 1': 'SpongifyChallenge',
    'Spongify Challenge - Secret 2': 'SpongifyChallenge',
    'Spongify Challenge - Secret 3': 'SpongifyChallenge',
    'Spongify Challenge - Secret 4': 'SpongifyChallenge',
    'Spongify Challenge - Secret 5': 'SpongifyChallenge',
    'Spongify Challenge - Secret 6': 'SpongifyChallenge',
    'Spongify Challenge - Secret 7': 'SpongifyChallenge',
    'Spongify Challenge - Secret 8': 'SpongifyChallenge',
    'Spongify Challenge - Secret 9': 'SpongifyChallenge',
    'Spongify Challenge - Secret 10': 'SpongifyChallenge',
    'Spongify Challenge - Secret 11': 'SpongifyChallenge',
    'Spongify Challenge - Secret 12': 'SpongifyChallenge',
    'Spongify Challenge - Secret 13': 'SpongifyChallenge',
    'Spongify Challenge - Secret 14': 'SpongifyChallenge',
    'Spongify Challenge - Secret 15': 'SpongifyChallenge',
    'Spongify Challenge - Secret 16': 'SpongifyChallenge',
    'Whomping Willow - Secret 1': 'WhompingWillow',
    'Whomping Willow - Secret 2': 'WhompingWillow',
    'Gryffindor Challenge - Secret 1': 'GryffindorChallenge',
    'Gryffindor Challenge - Secret 2': 'GryffindorChallenge',
    'Gryffindor Challenge - Secret 3': 'GryffindorChallenge',
    'Gryffindor Challenge - Secret 4': 'GryffindorChallenge',
    'Gryffindor Challenge - Secret 5': 'GryffindorChallenge',
    'Gryffindor Challenge - Secret 6': 'GryffindorChallenge',
    'Gryffindor Challenge - Secret 7': 'GryffindorChallenge',
    'Gryffindor Challenge - Secret 8': 'GryffindorChallenge',
    'Gryffindor Challenge - Secret 9': 'GryffindorChallenge',
    'Rictusempra Challenge - Challenge Star 3': 'RictusempraChallenge',
    'Rictusempra Challenge - Challenge Star 10': 'RictusempraChallenge',
    'Rictusempra Challenge - Challenge Star 2': 'RictusempraChallenge',
    'Rictusempra Challenge - Challenge Star 6': 'RictusempraChallenge',
    'Rictusempra Challenge - Challenge Star 1': 'RictusempraChallenge',
    'Rictusempra Challenge - Challenge Star 4': 'RictusempraChallenge',
    'Rictusempra Challenge - Challenge Star 8': 'RictusempraChallenge',
    'Rictusempra Challenge - Challenge Star 5': 'RictusempraChallenge',
    'Rictusempra Challenge - Challenge Star 7': 'RictusempraChallenge',
    'Rictusempra Challenge - Challenge Star 9': 'RictusempraChallenge',
    'Skurge Challenge - Challenge Star 1': 'SkurgeChallenge',
    'Skurge Challenge - Challenge Star 2': 'SkurgeChallenge',
    'Skurge Challenge - Challenge Star 3': 'SkurgeChallenge',
    'Skurge Challenge - Challenge Star 4': 'SkurgeChallenge',
    'Skurge Challenge - Challenge Star 5': 'SkurgeChallenge',
    'Skurge Challenge - Challenge Star 6': 'SkurgeChallenge',
    'Skurge Challenge - Challenge Star 7': 'SkurgeChallenge',
    'Skurge Challenge - Challenge Star 10': 'SkurgeChallenge',
    'Skurge Challenge - Challenge Star 9': 'SkurgeChallenge',
    'Skurge Challenge - Challenge Star 8': 'SkurgeChallenge',
    'Diffindo Challenge - Challenge Star 8': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 14': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 9': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 12': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 2': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 4': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 5': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 6': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 11': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 10': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 3': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 7': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 13': 'DiffindoChallenge',
    'Diffindo Challenge - Challenge Star 1': 'DiffindoChallenge',
    'Spongify Challenge - Challenge Star 1': 'SpongifyChallenge',
    'Spongify Challenge - Challenge Star 3': 'SpongifyChallenge',
    'Spongify Challenge - Challenge Star 2': 'SpongifyChallenge',
    'Spongify Challenge - Challenge Star 4': 'SpongifyChallenge',
    'Spongify Challenge - Challenge Star 5': 'SpongifyChallenge',
    'Spongify Challenge - Challenge Star 6': 'SpongifyChallenge',
    'Spongify Challenge - Challenge Star 7': 'SpongifyChallenge',
    'Spongify Challenge - Challenge Star 8': 'SpongifyChallenge',
    'Spongify Challenge - Challenge Star 9': 'SpongifyChallenge',
    'Spongify Challenge - Challenge Star 10': 'SpongifyChallenge',
    'Gryffindor Challenge - Challenge Star 7': 'GryffindorChallenge',
    'Gryffindor Challenge - Challenge Star 8': 'GryffindorChallenge',
    'Gryffindor Challenge - Challenge Star 9': 'GryffindorChallenge',
    'Gryffindor Challenge - Challenge Star 1': 'GryffindorChallenge',
    'Gryffindor Challenge - Challenge Star 2': 'GryffindorChallenge',
    'Gryffindor Challenge - Challenge Star 3': 'GryffindorChallenge',
    'Gryffindor Challenge - Challenge Star 6': 'GryffindorChallenge',
    'Gryffindor Challenge - Challenge Star 4': 'GryffindorChallenge',
    'Gryffindor Challenge - Challenge Star 5': 'GryffindorChallenge',
    'Gryffindor Challenge - Challenge Star 10': 'GryffindorChallenge',
    'Boomslang Level - Complete': 'BoomslangLevel',
    'Bicorn Level - Complete': 'BicornLevel',
    'Goyle Level - Complete': 'GoyleLevel',
    'Forbidden Forest - Complete': 'ForbiddenForest',
    'Chamber of Secrets - Complete': 'ChamberOfSecrets',
    'Whomping Willow - Complete': 'WhompingWillow',
    'Slytherin Common Room - Complete': 'SlytherinCommon',
    'Rictusempra Challenge - Complete': 'RictusempraChallenge',
    'Skurge Challenge - Complete': 'SkurgeChallenge',
    'Diffindo Challenge - Complete': 'DiffindoChallenge',
    'Spongify Challenge - Complete': 'SpongifyChallenge',
    'Gryffindor Challenge - Complete': 'GryffindorChallenge',
    'Entry Hall - Card Vendor 1': 'EntryHall',
    'Entry Hall - Card Vendor 2': 'EntryHall',
    'Entry Hall - Card Vendor 3': 'EntryHall',
    'Entry Hall - Ingredient Vendor 1': 'EntryHall',
    'Entry Hall - Ingredient Vendor 2': 'EntryHall',
    'Entry Hall - Ingredient Vendor 3': 'EntryHall',
    'Grand Staircase - Card Vendor 1': 'GrandStaircase',
    'Grand Staircase - Card Vendor 2': 'GrandStaircase',
    'Grand Staircase - Ingredient Vendor 1': 'GrandStaircase',
    'Castle Exterior - Card Vendor 1': 'CastleExterior',
    'Castle Exterior - Card Vendor 2': 'CastleExterior',
    'Castle Exterior - Ingredient Vendor 1': 'CastleExterior',
    'Castle Exterior - Ingredient Vendor 2': 'CastleExterior',
}

LOCATION_GROUPS: dict[str, str] = {
    'Learned Rictusempra': 'Classrooms',
    'Learned Skurge': 'Classrooms',
    'Learned Diffindo': 'Classrooms',
    'Learned Spongify': 'Classrooms',
    'Bicorn Level - Card Agrippa': 'CardLocations',
    'Entry Hall - Card Alderton': 'CardLocations',
    'Rictusempra Challenge - Card Barbary': 'CardLocations',
    'Grand Staircase - Card Barkwith': 'CardLocations',
    'Skurge Challenge - Card Belby': 'CardLocations',
    'Grand Staircase - Card Blane': 'CardLocations',
    'Goyle Level - Card Bloxam': 'CardLocations',
    'Grand Staircase - Card Bonham': 'CardLocations',
    'Skurge Challenge - Card Catchlove': 'CardLocations',
    'Chamber of Secrets - Card Elphick': 'CardLocations',
    'Grand Staircase - Card Ethelred': 'CardLocations',
    'Forbidden Forest - Card Fancourt': 'CardLocations',
    'Bicorn Level - Card Goshawk': 'CardLocations',
    'Rictusempra Challenge - Card Graves': 'CardLocations',
    'Entry Hall - Card Gunhilda': 'CardLocations',
    'Grand Staircase - Card Hipworth': 'CardLocations',
    'Skurge Challenge - Card Kegg': 'CardLocations',
    'Diffindo Challenge - Card Ketteridge': 'CardLocations',
    'Castle Exterior - Card Marjoribanks': 'CardLocations',
    'Spongify Challenge - Card Merlin': 'CardLocations',
    'Diffindo Challenge - Card Merwyn': 'CardLocations',
    "Dumbledore's Study - Card Muldoon": 'CardLocations',
    'Forbidden Forest - Card Ollerton': 'CardLocations',
    'Bicorn Level - Card Peakes': 'CardLocations',
    'Slytherin Common Room - Card Pilliwickle': 'CardLocations',
    'Slytherin Common Room - Card Platt': 'CardLocations',
    'Goyle Level - Card Plumpton': 'CardLocations',
    'Spongify Challenge - Card Po': 'CardLocations',
    'Castle Exterior - Card Pokeby': 'CardLocations',
    'Entry Hall - Card Sawbridge': 'CardLocations',
    'Forbidden Forest - Card Scamander': 'CardLocations',
    'Whomping Willow - Card Starkey': 'CardLocations',
    'Goyle Level - Card Stroulger': 'CardLocations',
    'Bicorn Level - Card Stump': 'CardLocations',
    'Castle Exterior - Card Sweeting': 'CardLocations',
    'Castle Exterior - Card Sykes': 'CardLocations',
    'Rictusempra Challenge - Card Thruston': 'CardLocations',
    'Boomslang Level - Card Toke': 'CardLocations',
    'Castle Exterior - Card Twonk': 'CardLocations',
    'Diffindo Challenge - Card Ulric': 'CardLocations',
    'Grand Staircase - Card Vablatsky': 'CardLocations',
    'Slytherin Common Room - Card Waffling': 'CardLocations',
    'Rictusempra Challenge - Card Wagtail': 'CardLocations',
    'Spongify Challenge - Card Warbeck': 'CardLocations',
    'Forbidden Forest - Card Wellbeloved': 'CardLocations',
    'Skurge Challenge - Card Wenlock': 'CardLocations',
    'Goyle Level - Card Whitehorn': 'CardLocations',
    'Rictusempra Challenge - Card Wintringham': 'CardLocations',
    'Diffindo Challenge - Card Withers': 'CardLocations',
    'Spongify Challenge - Card Woodcroft': 'CardLocations',
    'Entry Hall - Card Andros': 'CardLocations',
    "Dumbledore's Study - Card Beamish": 'CardLocations',
    'Rictusempra Challenge - Card Chittock': 'CardLocations',
    'Goyle Level - Card Circe': 'CardLocations',
    'Slytherin Common Room - Card Clagg': 'CardLocations',
    'Forbidden Forest - Card Cliodne': 'CardLocations',
    'Bicorn Level - Card Cronk': 'CardLocations',
    'Rictusempra Challenge - Card Crumb': 'CardLocations',
    'Entry Hall - Card Dodderidge': 'CardLocations',
    'Rictusempra Challenge - Card Duke': 'CardLocations',
    'Slytherin Common Room - Card Fay': 'CardLocations',
    'Skurge Challenge - Card Fulbert': 'CardLocations',
    'Spongify Challenge - Card Furmage': 'CardLocations',
    'Skurge Challenge - Card Gregory': 'CardLocations',
    'Spongify Challenge - Card Grunnion': 'CardLocations',
    'Entry Hall - Card Jones': 'CardLocations',
    'Grand Staircase - Card Lufkin': 'CardLocations',
    'Grand Staircase - Card Maeve': 'CardLocations',
    'Entry Hall - Card Montmorency': 'CardLocations',
    'Entry Hall - Card Mopsus': 'CardLocations',
    'Bicorn Level - Card Nutcombe': 'CardLocations',
    'Castle Exterior - Card Oglethorpe': 'CardLocations',
    'Grand Staircase - Card Oldridge': 'CardLocations',
    'Forbidden Forest - Card Oliphant': 'CardLocations',
    'Castle Exterior - Card Plunkett': 'CardLocations',
    'Spongify Challenge - Card Rastrick': 'CardLocations',
    'Diffindo Challenge - Card Shimpling': 'CardLocations',
    'Entry Hall - Card Shingleton': 'CardLocations',
    'Diffindo Challenge - Card Smethwyck': 'CardLocations',
    'Diffindo Challenge - Card Stalk': 'CardLocations',
    'Spongify Challenge - Card Summerbee': 'CardLocations',
    'Diffindo Challenge - Card Thurkell': 'CardLocations',
    'Grand Staircase - Card Toothill': 'CardLocations',
    'Rictusempra Challenge - Card Tremlett': 'CardLocations',
    'Boomslang Level - Card Tugwood': 'CardLocations',
    'Castle Exterior - Card Wadcock': 'CardLocations',
    'Entry Hall - Card Wendelin': 'CardLocations',
    'Goyle Level - Card Wildsmith': 'CardLocations',
    'Entry Hall - Card Wright': 'CardLocations',
    'Castle Exterior - Card Youdle': 'CardLocations',
    'Gold Card Room - Card Bott': 'CardLocations',
    'Gold Card Room - Card Dumbledore': 'CardLocations',
    'Gold Card Room - Card Gryffindor': 'CardLocations',
    'Gold Card Room - Card Herpo': 'CardLocations',
    'Gold Card Room - Card Hufflepuff': 'CardLocations',
    'Gold Card Room - Card Knightley': 'CardLocations',
    'Gold Card Room - Card Paracelsus': 'CardLocations',
    'Gold Card Room - Card Pinkstone': 'CardLocations',
    'Gold Card Room - Card Potter': 'CardLocations',
    'Gold Card Room - Card Ravenclaw': 'CardLocations',
    'Gold Card Room - Card Slytherin': 'CardLocations',
    'Castle Exterior - Nimbus 2001': 'QuidditchPurchases',
    'Castle Exterior - Quidditch Armour': 'QuidditchPurchases',
    'Duelling Club - Duel Rank 1': 'Duels',
    'Duelling Club - Duel Rank 2': 'Duels',
    'Duelling Club - Duel Rank 3': 'Duels',
    'Duelling Club - Duel Rank 4': 'Duels',
    'Duelling Club - Duel Rank 5': 'Duels',
    'Duelling Club - Duel Rank 6': 'Duels',
    'Duelling Club - Duel Rank 7': 'Duels',
    'Duelling Club - Duel Rank 8': 'Duels',
    'Duelling Club - Duel Rank 9': 'Duels',
    'Duelling Club - Duel Rank 10': 'Duels',
    'Quidditch - Match 1 (Hufflepuff)': 'QuidditchMatches',
    'Quidditch - Match 2 (Ravenclaw)': 'QuidditchMatches',
    'Quidditch - Match 3 (Slytherin)': 'QuidditchMatches',
    'Quidditch - Match 4 (Hufflepuff)': 'QuidditchMatches',
    'Quidditch - Match 5 (Ravenclaw)': 'QuidditchMatches',
    'Quidditch - Match 6 (Slytherin)': 'QuidditchMatches',
    'Rictusempra Challenge - Beat Par Time': 'SpellChallengeTimes',
    'Skurge Challenge - Beat Par Time': 'SpellChallengeTimes',
    'Diffindo Challenge - Beat Par Time': 'SpellChallengeTimes',
    'Spongify Challenge - Beat Par Time': 'SpellChallengeTimes',
    'Bicorn Level - Secret 2': 'Secrets',
    'Bicorn Level - Secret 1': 'Secrets',
    'Bicorn Level - Secret 6': 'Secrets',
    'Bicorn Level - Secret 3': 'Secrets',
    'Bicorn Level - Secret 4': 'Secrets',
    'Bicorn Level - Secret 5': 'Secrets',
    'Bicorn Level - Secret 7': 'Secrets',
    'Boomslang Level - Secret 3': 'Secrets',
    'Boomslang Level - Secret 2': 'Secrets',
    'Boomslang Level - Secret 1': 'Secrets',
    'Castle Exterior - Secret 1': 'Secrets',
    'Castle Exterior - Secret 2': 'Secrets',
    'Castle Exterior - Secret 3': 'Secrets',
    'Castle Exterior - Secret 4': 'Secrets',
    'Castle Exterior - Secret 5': 'Secrets',
    'Castle Exterior - Secret 6': 'Secrets',
    'Castle Exterior - Secret 7': 'Secrets',
    'Castle Exterior - Secret 8': 'Secrets',
    'Chamber of Secrets - Secret 3': 'Secrets',
    'Chamber of Secrets - Secret 2': 'Secrets',
    'Chamber of Secrets - Secret 1': 'Secrets',
    'Chamber of Secrets - Secret 5': 'Secrets',
    'Chamber of Secrets - Secret 4': 'Secrets',
    'Chamber of Secrets - Secret 6': 'Secrets',
    "Dumbledore's Study - Secret": 'Secrets',
    'Diffindo Challenge - Secret 1': 'Secrets',
    'Diffindo Challenge - Secret 2': 'Secrets',
    'Diffindo Challenge - Secret 3': 'Secrets',
    'Diffindo Challenge - Secret 5': 'Secrets',
    'Diffindo Challenge - Secret 6': 'Secrets',
    'Diffindo Challenge - Secret 4': 'Secrets',
    'Diffindo Challenge - Secret 7': 'Secrets',
    'Diffindo Challenge - Secret 8': 'Secrets',
    'Diffindo Challenge - Secret 9': 'Secrets',
    'Diffindo Challenge - Secret 10': 'Secrets',
    'Diffindo Challenge - Secret 11': 'Secrets',
    'Forbidden Forest - Secret 4': 'Secrets',
    'Forbidden Forest - Secret 3': 'Secrets',
    'Forbidden Forest - Secret 2': 'Secrets',
    'Forbidden Forest - Secret 1': 'Secrets',
    'Goyle Level - Secret 5': 'Secrets',
    'Goyle Level - Secret 6': 'Secrets',
    'Goyle Level - Secret 8': 'Secrets',
    'Goyle Level - Secret 7': 'Secrets',
    'Goyle Level - Secret 1': 'Secrets',
    'Goyle Level - Secret 3': 'Secrets',
    'Goyle Level - Secret 4': 'Secrets',
    'Goyle Level - Secret 2': 'Secrets',
    'Entry Hall - Secret 1': 'Secrets',
    'Entry Hall - Secret 2': 'Secrets',
    'Entry Hall - Secret 3': 'Secrets',
    'Entry Hall - Secret 4': 'Secrets',
    'Entry Hall - Secret 5': 'Secrets',
    'Entry Hall - Secret 6': 'Secrets',
    'Entry Hall - Secret 7': 'Secrets',
    'Entry Hall - Secret 8': 'Secrets',
    'Entry Hall - Secret 9': 'Secrets',
    'Entry Hall - Secret 10': 'Secrets',
    'Entry Hall - Secret 11': 'Secrets',
    'Entry Hall - Secret 12': 'Secrets',
    'Grand Staircase - Secret 1': 'Secrets',
    'Grand Staircase - Secret 2': 'Secrets',
    'Grand Staircase - Secret 3': 'Secrets',
    'Grand Staircase - Secret 4': 'Secrets',
    'Grand Staircase - Secret 5': 'Secrets',
    'Grand Staircase - Secret 6': 'Secrets',
    'Grand Staircase - Secret 7': 'Secrets',
    'Grand Staircase - Secret 8': 'Secrets',
    'Grand Staircase - Secret 9': 'Secrets',
    'Rictusempra Challenge - Secret 1': 'Secrets',
    'Rictusempra Challenge - Secret 3': 'Secrets',
    'Rictusempra Challenge - Secret 5': 'Secrets',
    'Rictusempra Challenge - Secret 4': 'Secrets',
    'Rictusempra Challenge - Secret 6': 'Secrets',
    'Rictusempra Challenge - Secret 7': 'Secrets',
    'Rictusempra Challenge - Secret 2': 'Secrets',
    'Skurge Challenge - Secret 1': 'Secrets',
    'Skurge Challenge - Secret 2': 'Secrets',
    'Skurge Challenge - Secret 3': 'Secrets',
    'Skurge Challenge - Secret 4': 'Secrets',
    'Skurge Challenge - Secret 5': 'Secrets',
    'Skurge Challenge - Secret 6': 'Secrets',
    'Skurge Challenge - Secret 7': 'Secrets',
    'Slytherin Common Room - Secret 7': 'Secrets',
    'Slytherin Common Room - Secret 6': 'Secrets',
    'Slytherin Common Room - Secret 5': 'Secrets',
    'Slytherin Common Room - Secret 8': 'Secrets',
    'Slytherin Common Room - Secret 4': 'Secrets',
    'Slytherin Common Room - Secret 3': 'Secrets',
    'Slytherin Common Room - Secret 2': 'Secrets',
    'Slytherin Common Room - Secret 1': 'Secrets',
    'Spongify Challenge - Secret 1': 'Secrets',
    'Spongify Challenge - Secret 2': 'Secrets',
    'Spongify Challenge - Secret 3': 'Secrets',
    'Spongify Challenge - Secret 4': 'Secrets',
    'Spongify Challenge - Secret 5': 'Secrets',
    'Spongify Challenge - Secret 6': 'Secrets',
    'Spongify Challenge - Secret 7': 'Secrets',
    'Spongify Challenge - Secret 8': 'Secrets',
    'Spongify Challenge - Secret 9': 'Secrets',
    'Spongify Challenge - Secret 10': 'Secrets',
    'Spongify Challenge - Secret 11': 'Secrets',
    'Spongify Challenge - Secret 12': 'Secrets',
    'Spongify Challenge - Secret 13': 'Secrets',
    'Spongify Challenge - Secret 14': 'Secrets',
    'Spongify Challenge - Secret 15': 'Secrets',
    'Spongify Challenge - Secret 16': 'Secrets',
    'Whomping Willow - Secret 1': 'Secrets',
    'Whomping Willow - Secret 2': 'Secrets',
    'Gryffindor Challenge - Secret 1': 'Secrets',
    'Gryffindor Challenge - Secret 2': 'Secrets',
    'Gryffindor Challenge - Secret 3': 'Secrets',
    'Gryffindor Challenge - Secret 4': 'Secrets',
    'Gryffindor Challenge - Secret 5': 'Secrets',
    'Gryffindor Challenge - Secret 6': 'Secrets',
    'Gryffindor Challenge - Secret 7': 'Secrets',
    'Gryffindor Challenge - Secret 8': 'Secrets',
    'Gryffindor Challenge - Secret 9': 'Secrets',
    'Rictusempra Challenge - Challenge Star 3': 'ChallengeStars',
    'Rictusempra Challenge - Challenge Star 10': 'ChallengeStars',
    'Rictusempra Challenge - Challenge Star 2': 'ChallengeStars',
    'Rictusempra Challenge - Challenge Star 6': 'ChallengeStars',
    'Rictusempra Challenge - Challenge Star 1': 'ChallengeStars',
    'Rictusempra Challenge - Challenge Star 4': 'ChallengeStars',
    'Rictusempra Challenge - Challenge Star 8': 'ChallengeStars',
    'Rictusempra Challenge - Challenge Star 5': 'ChallengeStars',
    'Rictusempra Challenge - Challenge Star 7': 'ChallengeStars',
    'Rictusempra Challenge - Challenge Star 9': 'ChallengeStars',
    'Skurge Challenge - Challenge Star 1': 'ChallengeStars',
    'Skurge Challenge - Challenge Star 2': 'ChallengeStars',
    'Skurge Challenge - Challenge Star 3': 'ChallengeStars',
    'Skurge Challenge - Challenge Star 4': 'ChallengeStars',
    'Skurge Challenge - Challenge Star 5': 'ChallengeStars',
    'Skurge Challenge - Challenge Star 6': 'ChallengeStars',
    'Skurge Challenge - Challenge Star 7': 'ChallengeStars',
    'Skurge Challenge - Challenge Star 10': 'ChallengeStars',
    'Skurge Challenge - Challenge Star 9': 'ChallengeStars',
    'Skurge Challenge - Challenge Star 8': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 8': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 14': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 9': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 12': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 2': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 4': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 5': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 6': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 11': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 10': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 3': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 7': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 13': 'ChallengeStars',
    'Diffindo Challenge - Challenge Star 1': 'ChallengeStars',
    'Spongify Challenge - Challenge Star 1': 'ChallengeStars',
    'Spongify Challenge - Challenge Star 3': 'ChallengeStars',
    'Spongify Challenge - Challenge Star 2': 'ChallengeStars',
    'Spongify Challenge - Challenge Star 4': 'ChallengeStars',
    'Spongify Challenge - Challenge Star 5': 'ChallengeStars',
    'Spongify Challenge - Challenge Star 6': 'ChallengeStars',
    'Spongify Challenge - Challenge Star 7': 'ChallengeStars',
    'Spongify Challenge - Challenge Star 8': 'ChallengeStars',
    'Spongify Challenge - Challenge Star 9': 'ChallengeStars',
    'Spongify Challenge - Challenge Star 10': 'ChallengeStars',
    'Gryffindor Challenge - Challenge Star 7': 'ChallengeStars',
    'Gryffindor Challenge - Challenge Star 8': 'ChallengeStars',
    'Gryffindor Challenge - Challenge Star 9': 'ChallengeStars',
    'Gryffindor Challenge - Challenge Star 1': 'ChallengeStars',
    'Gryffindor Challenge - Challenge Star 2': 'ChallengeStars',
    'Gryffindor Challenge - Challenge Star 3': 'ChallengeStars',
    'Gryffindor Challenge - Challenge Star 6': 'ChallengeStars',
    'Gryffindor Challenge - Challenge Star 4': 'ChallengeStars',
    'Gryffindor Challenge - Challenge Star 5': 'ChallengeStars',
    'Gryffindor Challenge - Challenge Star 10': 'ChallengeStars',
    'Boomslang Level - Complete': 'LevelCompletions',
    'Bicorn Level - Complete': 'LevelCompletions',
    'Goyle Level - Complete': 'LevelCompletions',
    'Forbidden Forest - Complete': 'LevelCompletions',
    'Chamber of Secrets - Complete': 'LevelCompletions',
    'Whomping Willow - Complete': 'LevelCompletions',
    'Slytherin Common Room - Complete': 'LevelCompletions',
    'Rictusempra Challenge - Complete': 'LevelCompletions',
    'Skurge Challenge - Complete': 'LevelCompletions',
    'Diffindo Challenge - Complete': 'LevelCompletions',
    'Spongify Challenge - Complete': 'LevelCompletions',
    'Gryffindor Challenge - Complete': 'LevelCompletions',
    'Entry Hall - Card Vendor 1': 'Tradersanity',
    'Entry Hall - Card Vendor 2': 'Tradersanity',
    'Entry Hall - Card Vendor 3': 'Tradersanity',
    'Entry Hall - Ingredient Vendor 1': 'Tradersanity',
    'Entry Hall - Ingredient Vendor 2': 'Tradersanity',
    'Entry Hall - Ingredient Vendor 3': 'Tradersanity',
    'Grand Staircase - Card Vendor 1': 'Tradersanity',
    'Grand Staircase - Card Vendor 2': 'Tradersanity',
    'Grand Staircase - Ingredient Vendor 1': 'Tradersanity',
    'Castle Exterior - Card Vendor 1': 'Tradersanity',
    'Castle Exterior - Card Vendor 2': 'Tradersanity',
    'Castle Exterior - Ingredient Vendor 1': 'Tradersanity',
    'Castle Exterior - Ingredient Vendor 2': 'Tradersanity',
}

# Map UScript card class name → AP location name. Used by the client to
# resolve a game CHECK to the right AP location for LocationChecks.
CARD_CLASS_TO_LOCATION_NAME: dict[str, str] = {
    'WCAgrippa': 'Bicorn Level - Card Agrippa',
    'WCAlderton': 'Entry Hall - Card Alderton',
    'WCBarbary': 'Rictusempra Challenge - Card Barbary',
    'WCBarkwith': 'Grand Staircase - Card Barkwith',
    'WCBelby': 'Skurge Challenge - Card Belby',
    'WCBlane': 'Grand Staircase - Card Blane',
    'WCBloxam': 'Goyle Level - Card Bloxam',
    'WCBonham': 'Grand Staircase - Card Bonham',
    'WCCatchlove': 'Skurge Challenge - Card Catchlove',
    'WCElphick': 'Chamber of Secrets - Card Elphick',
    'WCEthelred': 'Grand Staircase - Card Ethelred',
    'WCFancourt': 'Forbidden Forest - Card Fancourt',
    'WCGoshawk': 'Bicorn Level - Card Goshawk',
    'WCGraves': 'Rictusempra Challenge - Card Graves',
    'WCGunhilda': 'Entry Hall - Card Gunhilda',
    'WCHipworth': 'Grand Staircase - Card Hipworth',
    'WCKegg': 'Skurge Challenge - Card Kegg',
    'WCKetteridge': 'Diffindo Challenge - Card Ketteridge',
    'WCMarjoribanks': 'Castle Exterior - Card Marjoribanks',
    'WCMerlin': 'Spongify Challenge - Card Merlin',
    'WCMerwyn': 'Diffindo Challenge - Card Merwyn',
    'WCMuldoon': "Dumbledore's Study - Card Muldoon",
    'WCOllerton': 'Forbidden Forest - Card Ollerton',
    'WCPeakes': 'Bicorn Level - Card Peakes',
    'WCPilliwickle': 'Slytherin Common Room - Card Pilliwickle',
    'WCPlatt': 'Slytherin Common Room - Card Platt',
    'WCPlumpton': 'Goyle Level - Card Plumpton',
    'WCPo': 'Spongify Challenge - Card Po',
    'WCPokeby': 'Castle Exterior - Card Pokeby',
    'WCSawbridge': 'Entry Hall - Card Sawbridge',
    'WCScamander': 'Forbidden Forest - Card Scamander',
    'WCStarkey': 'Whomping Willow - Card Starkey',
    'WCStroulger': 'Goyle Level - Card Stroulger',
    'WCStump': 'Bicorn Level - Card Stump',
    'WCSweeting': 'Castle Exterior - Card Sweeting',
    'WCSykes': 'Castle Exterior - Card Sykes',
    'WCThruston': 'Rictusempra Challenge - Card Thruston',
    'WCToke': 'Boomslang Level - Card Toke',
    'WCTwonk': 'Castle Exterior - Card Twonk',
    'WCUlric': 'Diffindo Challenge - Card Ulric',
    'WCVablatsky': 'Grand Staircase - Card Vablatsky',
    'WCWaffling': 'Slytherin Common Room - Card Waffling',
    'WCWagtail': 'Rictusempra Challenge - Card Wagtail',
    'WCWarbeck': 'Spongify Challenge - Card Warbeck',
    'WCWellbeloved': 'Forbidden Forest - Card Wellbeloved',
    'WCWenlock': 'Skurge Challenge - Card Wenlock',
    'WCWhitehorn': 'Goyle Level - Card Whitehorn',
    'WCWintringham': 'Rictusempra Challenge - Card Wintringham',
    'WCWithers': 'Diffindo Challenge - Card Withers',
    'WCWoodcroft': 'Spongify Challenge - Card Woodcroft',
    'WCAndros': 'Entry Hall - Card Andros',
    'WCBeamish': "Dumbledore's Study - Card Beamish",
    'WCChittock': 'Rictusempra Challenge - Card Chittock',
    'WCCirce': 'Goyle Level - Card Circe',
    'WCClagg': 'Slytherin Common Room - Card Clagg',
    'WCCliodne': 'Forbidden Forest - Card Cliodne',
    'WCCronk': 'Bicorn Level - Card Cronk',
    'WCCrumb': 'Rictusempra Challenge - Card Crumb',
    'WCDodderidge': 'Entry Hall - Card Dodderidge',
    'WCDuke': 'Rictusempra Challenge - Card Duke',
    'WCFay': 'Slytherin Common Room - Card Fay',
    'WCFulbert': 'Skurge Challenge - Card Fulbert',
    'WCFurmage': 'Spongify Challenge - Card Furmage',
    'WCGregory': 'Skurge Challenge - Card Gregory',
    'WCGrunnion': 'Spongify Challenge - Card Grunnion',
    'WCJones': 'Entry Hall - Card Jones',
    'WCLufkin': 'Grand Staircase - Card Lufkin',
    'WCMaeve': 'Grand Staircase - Card Maeve',
    'WCMontmorency': 'Entry Hall - Card Montmorency',
    'WCMopsus': 'Entry Hall - Card Mopsus',
    'WCNutcombe': 'Bicorn Level - Card Nutcombe',
    'WCOglethorpe': 'Castle Exterior - Card Oglethorpe',
    'WCOldridge': 'Grand Staircase - Card Oldridge',
    'WCOliphant': 'Forbidden Forest - Card Oliphant',
    'WCPlunkett': 'Castle Exterior - Card Plunkett',
    'WCRastrick': 'Spongify Challenge - Card Rastrick',
    'WCShimpling': 'Diffindo Challenge - Card Shimpling',
    'WCShingleton': 'Entry Hall - Card Shingleton',
    'WCSmethwyck': 'Diffindo Challenge - Card Smethwyck',
    'WCStalk': 'Diffindo Challenge - Card Stalk',
    'WCSummerbee': 'Spongify Challenge - Card Summerbee',
    'WCThurkell': 'Diffindo Challenge - Card Thurkell',
    'WCToothill': 'Grand Staircase - Card Toothill',
    'WCTremlett': 'Rictusempra Challenge - Card Tremlett',
    'WCTugwood': 'Boomslang Level - Card Tugwood',
    'WCWadcock': 'Castle Exterior - Card Wadcock',
    'WCWendelin': 'Entry Hall - Card Wendelin',
    'WCWildsmith': 'Goyle Level - Card Wildsmith',
    'WCWright': 'Entry Hall - Card Wright',
    'WCYoudle': 'Castle Exterior - Card Youdle',
    'WCBott': 'Gold Card Room - Card Bott',
    'WCDumbledore': 'Gold Card Room - Card Dumbledore',
    'WCGriffindor': 'Gold Card Room - Card Gryffindor',
    'WCHerpo': 'Gold Card Room - Card Herpo',
    'WCHufflepuff': 'Gold Card Room - Card Hufflepuff',
    'WCKnightley': 'Gold Card Room - Card Knightley',
    'WCParacelsus': 'Gold Card Room - Card Paracelsus',
    'WCPinkstone': 'Gold Card Room - Card Pinkstone',
    'WCPotter': 'Gold Card Room - Card Potter',
    'WCRavenclaw': 'Gold Card Room - Card Ravenclaw',
    'WCSlytherin': 'Gold Card Room - Card Slytherin',
}

# Map game-side card Id (the UScript WC*.uc default Id property) → AP
# location name. Client receives 'CHECK <int>' from the mod and uses
# this to find the AP location to send LocationChecks for.
CARD_GAME_ID_TO_LOCATION_NAME: dict[int, str] = {
    1: 'Spongify Challenge - Card Merlin',
    2: 'Bicorn Level - Card Agrippa',
    3: 'Slytherin Common Room - Card Clagg',
    4: 'Bicorn Level - Card Stump',
    5: 'Castle Exterior - Card Pokeby',
    6: 'Bicorn Level - Card Peakes',
    7: 'Whomping Willow - Card Starkey',
    8: 'Diffindo Challenge - Card Shimpling',
    9: 'Entry Hall - Card Gunhilda',
    10: "Dumbledore's Study - Card Muldoon",
    11: 'Gold Card Room - Card Herpo',
    12: 'Diffindo Challenge - Card Merwyn',
    13: 'Entry Hall - Card Andros',
    14: 'Skurge Challenge - Card Fulbert',
    15: 'Gold Card Room - Card Paracelsus',
    16: 'Forbidden Forest - Card Cliodne',
    17: 'Slytherin Common Room - Card Fay',
    18: 'Diffindo Challenge - Card Ulric',
    19: 'Forbidden Forest - Card Scamander',
    20: 'Entry Hall - Card Wendelin',
    21: 'Diffindo Challenge - Card Withers',
    22: 'Goyle Level - Card Circe',
    23: 'Rictusempra Challenge - Card Chittock',
    24: 'Slytherin Common Room - Card Waffling',
    25: 'Forbidden Forest - Card Fancourt',
    26: 'Entry Hall - Card Sawbridge',
    27: 'Castle Exterior - Card Plunkett',
    28: 'Boomslang Level - Card Toke',
    29: 'Entry Hall - Card Alderton',
    30: 'Grand Staircase - Card Lufkin',
    31: 'Grand Staircase - Card Blane',
    32: 'Skurge Challenge - Card Wenlock',
    33: 'Castle Exterior - Card Marjoribanks',
    34: 'Rictusempra Challenge - Card Tremlett',
    35: 'Entry Hall - Card Wright',
    36: 'Castle Exterior - Card Wadcock',
    37: 'Grand Staircase - Card Vablatsky',
    38: 'Grand Staircase - Card Oldridge',
    39: 'Entry Hall - Card Jones',
    40: 'Gold Card Room - Card Pinkstone',
    41: 'Gold Card Room - Card Gryffindor',
    42: 'Bicorn Level - Card Cronk',
    43: 'Castle Exterior - Card Youdle',
    44: 'Goyle Level - Card Whitehorn',
    45: 'Castle Exterior - Card Oglethorpe',
    46: 'Bicorn Level - Card Goshawk',
    47: 'Goyle Level - Card Stroulger',
    48: 'Gold Card Room - Card Slytherin',
    49: 'Diffindo Challenge - Card Ketteridge',
    50: 'Grand Staircase - Card Barkwith',
    51: 'Grand Staircase - Card Ethelred',
    52: 'Spongify Challenge - Card Summerbee',
    53: 'Skurge Challenge - Card Catchlove',
    54: 'Entry Hall - Card Shingleton',
    55: 'Bicorn Level - Card Nutcombe',
    56: 'Rictusempra Challenge - Card Crumb',
    57: 'Forbidden Forest - Card Ollerton',
    58: 'Grand Staircase - Card Hipworth',
    59: 'Skurge Challenge - Card Gregory',
    60: 'Entry Hall - Card Montmorency',
    61: 'Castle Exterior - Card Sweeting',
    62: 'Goyle Level - Card Wildsmith',
    63: 'Rictusempra Challenge - Card Wintringham',
    64: 'Castle Exterior - Card Sykes',
    65: 'Forbidden Forest - Card Oliphant',
    66: 'Skurge Challenge - Card Belby',
    67: 'Slytherin Common Room - Card Pilliwickle',
    68: 'Rictusempra Challenge - Card Duke',
    69: 'Gold Card Room - Card Bott',
    70: 'Diffindo Challenge - Card Smethwyck',
    71: 'Grand Staircase - Card Maeve',
    72: 'Gold Card Room - Card Hufflepuff',
    73: 'Entry Hall - Card Mopsus',
    74: 'Gold Card Room - Card Knightley',
    75: 'Grand Staircase - Card Bonham',
    76: 'Rictusempra Challenge - Card Wagtail',
    77: 'Castle Exterior - Card Twonk',
    78: 'Rictusempra Challenge - Card Thruston',
    79: "Dumbledore's Study - Card Beamish",
    80: 'Goyle Level - Card Bloxam',
    81: 'Spongify Challenge - Card Po',
    82: 'Gold Card Room - Card Ravenclaw',
    83: 'Goyle Level - Card Plumpton',
    84: 'Skurge Challenge - Card Kegg',
    85: 'Diffindo Challenge - Card Stalk',
    86: 'Forbidden Forest - Card Wellbeloved',
    87: 'Diffindo Challenge - Card Thurkell',
    88: 'Spongify Challenge - Card Warbeck',
    89: 'Grand Staircase - Card Toothill',
    90: 'Boomslang Level - Card Tugwood',
    91: 'Chamber of Secrets - Card Elphick',
    92: 'Spongify Challenge - Card Rastrick',
    93: 'Rictusempra Challenge - Card Barbary',
    94: 'Rictusempra Challenge - Card Graves',
    95: 'Slytherin Common Room - Card Platt',
    96: 'Spongify Challenge - Card Woodcroft',
    97: 'Spongify Challenge - Card Grunnion',
    98: 'Spongify Challenge - Card Furmage',
    99: 'Entry Hall - Card Dodderidge',
    100: 'Gold Card Room - Card Potter',
    101: 'Gold Card Room - Card Dumbledore',
}

GOLD_CARD_ROOM_LOCATIONS: frozenset = frozenset({
    'Gold Card Room - Card Bott',
    'Gold Card Room - Card Dumbledore',
    'Gold Card Room - Card Gryffindor',
    'Gold Card Room - Card Herpo',
    'Gold Card Room - Card Hufflepuff',
    'Gold Card Room - Card Knightley',
    'Gold Card Room - Card Paracelsus',
    'Gold Card Room - Card Pinkstone',
    'Gold Card Room - Card Potter',
    'Gold Card Room - Card Ravenclaw',
    'Gold Card Room - Card Slytherin',
})

# Secrets in one-way (un-replayable) levels: permanently lost once
# the level is left behind. HP2World keeps these filler-only unless
# allow_secrets_progression is set AND every item they depend on is
# precollected (so the player is guaranteed to hold it while passing
# through the level the one time it is reachable).
MISSABLE_SECRETS: frozenset = frozenset({
    'Bicorn Level - Secret 1',
    'Bicorn Level - Secret 2',
    'Bicorn Level - Secret 3',
    'Bicorn Level - Secret 4',
    'Bicorn Level - Secret 5',
    'Bicorn Level - Secret 6',
    'Bicorn Level - Secret 7',
    'Boomslang Level - Secret 1',
    'Boomslang Level - Secret 2',
    'Boomslang Level - Secret 3',
    'Chamber of Secrets - Secret 1',
    'Chamber of Secrets - Secret 2',
    'Chamber of Secrets - Secret 3',
    'Chamber of Secrets - Secret 4',
    'Chamber of Secrets - Secret 5',
    'Chamber of Secrets - Secret 6',
    "Dumbledore's Study - Secret",
    'Forbidden Forest - Secret 1',
    'Forbidden Forest - Secret 2',
    'Forbidden Forest - Secret 3',
    'Forbidden Forest - Secret 4',
    'Goyle Level - Secret 1',
    'Goyle Level - Secret 2',
    'Goyle Level - Secret 3',
    'Goyle Level - Secret 4',
    'Goyle Level - Secret 5',
    'Goyle Level - Secret 6',
    'Goyle Level - Secret 7',
    'Goyle Level - Secret 8',
    'Slytherin Common Room - Secret 1',
    'Slytherin Common Room - Secret 2',
    'Slytherin Common Room - Secret 3',
    'Slytherin Common Room - Secret 4',
    'Slytherin Common Room - Secret 5',
    'Slytherin Common Room - Secret 6',
    'Slytherin Common Room - Secret 7',
    'Slytherin Common Room - Secret 8',
    'Whomping Willow - Secret 1',
    'Whomping Willow - Secret 2',
})

# Item names appearing in (region entry AND location requires)
# for each missable secret. Vanilla-only: the missable system is
# a vanilla concept (open castle replays every level), so there is
# no open castle dependency table. A subset of the precollected
# starting inventory means the secret is reachable from the start.
MISSABLE_SECRET_DEPS_VANILLA: dict[str, list[str]] = {
    'Bicorn Level - Secret 2': ['Alohomora', 'Bicorn Level Key', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Bicorn Level - Secret 1': ['Alohomora', 'Bicorn Level Key', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Bicorn Level - Secret 6': ['Alohomora', 'Bicorn Level Key', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Bicorn Level - Secret 3': ['Alohomora', 'Bicorn Level Key', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Bicorn Level - Secret 4': ['Alohomora', 'Bicorn Level Key', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Bicorn Level - Secret 5': ['Alohomora', 'Bicorn Level Key', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Bicorn Level - Secret 7': ['Alohomora', 'Bicorn Level Key', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Boomslang Level - Secret 3': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Boomslang Level - Secret 2': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Boomslang Level - Secret 1': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Chamber of Secrets - Secret 3': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Chamber of Secrets Key', 'Diffindo', 'Flipendo', 'Forbidden Forest Key', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key', 'Spongify'],
    'Chamber of Secrets - Secret 2': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Chamber of Secrets Key', 'Diffindo', 'Flipendo', 'Forbidden Forest Key', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key', 'Spongify'],
    'Chamber of Secrets - Secret 1': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Chamber of Secrets Key', 'Diffindo', 'Flipendo', 'Forbidden Forest Key', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key', 'Spongify'],
    'Chamber of Secrets - Secret 5': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Chamber of Secrets Key', 'Diffindo', 'Flipendo', 'Forbidden Forest Key', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key', 'Spongify'],
    'Chamber of Secrets - Secret 4': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Chamber of Secrets Key', 'Diffindo', 'Flipendo', 'Forbidden Forest Key', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key', 'Spongify'],
    'Chamber of Secrets - Secret 6': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Chamber of Secrets Key', 'Diffindo', 'Flipendo', 'Forbidden Forest Key', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key', 'Spongify'],
    "Dumbledore's Study - Secret": ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Lumos', 'Rictusempra', 'Skurge'],
    'Forbidden Forest - Secret 4': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Forbidden Forest Key', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key', 'Spongify'],
    'Forbidden Forest - Secret 3': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Forbidden Forest Key', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key', 'Spongify'],
    'Forbidden Forest - Secret 2': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Forbidden Forest Key', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key', 'Spongify'],
    'Forbidden Forest - Secret 1': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Forbidden Forest Key', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key', 'Spongify'],
    'Goyle Level - Secret 5': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge'],
    'Goyle Level - Secret 6': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge'],
    'Goyle Level - Secret 8': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge'],
    'Goyle Level - Secret 7': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge'],
    'Goyle Level - Secret 1': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge'],
    'Goyle Level - Secret 3': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge'],
    'Goyle Level - Secret 4': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge'],
    'Goyle Level - Secret 2': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge'],
    'Slytherin Common Room - Secret 7': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key'],
    'Slytherin Common Room - Secret 6': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key'],
    'Slytherin Common Room - Secret 5': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key'],
    'Slytherin Common Room - Secret 8': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key'],
    'Slytherin Common Room - Secret 4': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key'],
    'Slytherin Common Room - Secret 3': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key'],
    'Slytherin Common Room - Secret 2': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key'],
    'Slytherin Common Room - Secret 1': ['Alohomora', 'Bicorn Level Key', 'Boomslang Level Key', 'Diffindo', 'Flipendo', 'Goyle Level Key', 'Lumos', 'Rictusempra', 'Skurge', 'Slytherin Common Room Key'],
    'Whomping Willow - Secret 1': ['Alohomora', 'Lumos'],
    'Whomping Willow - Secret 2': ['Alohomora', 'Flipendo', 'Lumos'],
}
