"""Auto-generated. Do not edit by hand; regenerate from data/logic_vanilla.yaml + data/logic_bingo.yaml."""

from typing import Callable

from BaseClasses import CollectionState

START_REGION: str = 'Menu'

REGION_NAMES: list[str] = ['BicornLevel', 'BoomslangLevel', 'CastleExterior', 'ChamberOfSecrets', 'DiffindoChallenge', 'DuelingClub', 'DumbledoreStudy', 'ForbiddenForest', 'GoldCardRoom', 'GoyleLevel', 'GryffindorChallenge', 'Hogwarts', 'Menu', 'Quidditch', 'RictusempraChallenge', 'SkurgeChallenge', 'SlytherinCommon', 'SpongifyChallenge', 'WhompingWillow']

# region_name -> rule(state, player) -> bool. Mode-dependent: HP2World
# selects vanilla or bingo at gen time via self.options.game_mode.
REGION_ENTRY_RULES_VANILLA: dict[str, Callable[[CollectionState, int], bool]] = {
    'BicornLevel': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Bicorn Level Key', player),
    'BoomslangLevel': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player)  and  state.has('Bicorn Level Key', player)  and  state.has('Boomslang Level Key', player),
    'CastleExterior': lambda state, player: True,
    'ChamberOfSecrets': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player)  and  state.has('Spongify', player)  and  state.has('Chamber of Secrets Key', player),
    'DiffindoChallenge': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player)  and  state.has('Diffindo Challenge Key', player),
    'DuelingClub': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Duelling Key', player),
    'DumbledoreStudy': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player),
    'ForbiddenForest': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player)  and  state.has('Spongify', player)  and  state.has('Bicorn Level Key', player)  and  state.has('Boomslang Level Key', player)  and  state.has('Goyle Level Key', player)  and  state.has('Slytherin Common Room Key', player)  and  state.has('Forbidden Forest Key', player),
    'GoldCardRoom': lambda state, player: (state.has('Silver Card - Andros', player)  and  state.has('Silver Card - Beamish', player)  and  state.has('Silver Card - Chittock', player)  and  state.has('Silver Card - Circe', player)  and  state.has('Silver Card - Clagg', player)  and  state.has('Silver Card - Cliodne', player)  and  state.has('Silver Card - Cronk', player)  and  state.has('Silver Card - Crumb', player)  and  state.has('Silver Card - Dodderidge', player)  and  state.has('Silver Card - Duke', player)  and  state.has('Silver Card - Fay', player)  and  state.has('Silver Card - Fulbert', player)  and  state.has('Silver Card - Furmage', player)  and  state.has('Silver Card - Gregory', player)  and  state.has('Silver Card - Grunnion', player)  and  state.has('Silver Card - Jones', player)  and  state.has('Silver Card - Lufkin', player)  and  state.has('Silver Card - Maeve', player)  and  state.has('Silver Card - Montmorency', player)  and  state.has('Silver Card - Mopsus', player)  and  state.has('Silver Card - Nutcombe', player)  and  state.has('Silver Card - Oglethorpe', player)  and  state.has('Silver Card - Oldridge', player)  and  state.has('Silver Card - Oliphant', player)  and  state.has('Silver Card - Plunkett', player)  and  state.has('Silver Card - Rastrick', player)  and  state.has('Silver Card - Shimpling', player)  and  state.has('Silver Card - Shingleton', player)  and  state.has('Silver Card - Smethwyck', player)  and  state.has('Silver Card - Stalk', player)  and  state.has('Silver Card - Summerbee', player)  and  state.has('Silver Card - Thurkell', player)  and  state.has('Silver Card - Toothill', player)  and  state.has('Silver Card - Tremlett', player)  and  state.has('Silver Card - Tugwood', player)  and  state.has('Silver Card - Wadcock', player)  and  state.has('Silver Card - Wendelin', player)  and  state.has('Silver Card - Wildsmith', player)  and  state.has('Silver Card - Wright', player)  and  state.has('Silver Card - Youdle', player)),
    'GoyleLevel': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player)  and  state.has('Bicorn Level Key', player)  and  state.has('Boomslang Level Key', player)  and  state.has('Goyle Level Key', player),
    'GryffindorChallenge': lambda state, player: False,
    'Hogwarts': lambda state, player: True,
    'Quidditch': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Rictusempra', player)  and  state.has('Quidditch Key', player),
    'RictusempraChallenge': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Rictusempra Challenge Key', player),
    'SkurgeChallenge': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Skurge Challenge Key', player),
    'SlytherinCommon': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player)  and  state.has('Bicorn Level Key', player)  and  state.has('Boomslang Level Key', player)  and  state.has('Goyle Level Key', player)  and  state.has('Slytherin Common Room Key', player),
    'SpongifyChallenge': lambda state, player: state.has('Lumos', player)  and  state.has('Flipendo', player)  and  state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player)  and  state.has('Spongify', player)  and  state.has('Spongify Challenge Key', player),
    'WhompingWillow': lambda state, player: state.has('Whomping Willow Key', player),
}

REGION_ENTRY_RULES_BINGO: dict[str, Callable[[CollectionState, int], bool]] = {
    'BicornLevel': lambda state, player: state.has('Bicorn Level Key', player)  and  state.has('Skurge', player),
    'BoomslangLevel': lambda state, player: state.has('Boomslang Level Key', player)  and  state.has('Diffindo', player),
    'CastleExterior': lambda state, player: True,
    'ChamberOfSecrets': lambda state, player: state.has('Chamber of Secrets Key', player)  and  state.has('Alohomora', player),
    'DiffindoChallenge': lambda state, player: state.has('Diffindo Challenge Key', player)  and  state.has('Diffindo', player),
    'DuelingClub': lambda state, player: state.has('Duelling Key', player),
    'DumbledoreStudy': lambda state, player: state.has('Alohomora', player),
    'ForbiddenForest': lambda state, player: state.has('Forbidden Forest Key', player),
    'GoldCardRoom': lambda state, player: (state.has('Silver Card - Andros', player)  and  state.has('Silver Card - Beamish', player)  and  state.has('Silver Card - Chittock', player)  and  state.has('Silver Card - Circe', player)  and  state.has('Silver Card - Clagg', player)  and  state.has('Silver Card - Cliodne', player)  and  state.has('Silver Card - Cronk', player)  and  state.has('Silver Card - Crumb', player)  and  state.has('Silver Card - Dodderidge', player)  and  state.has('Silver Card - Duke', player)  and  state.has('Silver Card - Fay', player)  and  state.has('Silver Card - Fulbert', player)  and  state.has('Silver Card - Furmage', player)  and  state.has('Silver Card - Gregory', player)  and  state.has('Silver Card - Grunnion', player)  and  state.has('Silver Card - Jones', player)  and  state.has('Silver Card - Lufkin', player)  and  state.has('Silver Card - Maeve', player)  and  state.has('Silver Card - Montmorency', player)  and  state.has('Silver Card - Mopsus', player)  and  state.has('Silver Card - Nutcombe', player)  and  state.has('Silver Card - Oglethorpe', player)  and  state.has('Silver Card - Oldridge', player)  and  state.has('Silver Card - Oliphant', player)  and  state.has('Silver Card - Plunkett', player)  and  state.has('Silver Card - Rastrick', player)  and  state.has('Silver Card - Shimpling', player)  and  state.has('Silver Card - Shingleton', player)  and  state.has('Silver Card - Smethwyck', player)  and  state.has('Silver Card - Stalk', player)  and  state.has('Silver Card - Summerbee', player)  and  state.has('Silver Card - Thurkell', player)  and  state.has('Silver Card - Toothill', player)  and  state.has('Silver Card - Tremlett', player)  and  state.has('Silver Card - Tugwood', player)  and  state.has('Silver Card - Wadcock', player)  and  state.has('Silver Card - Wendelin', player)  and  state.has('Silver Card - Wildsmith', player)  and  state.has('Silver Card - Wright', player)  and  state.has('Silver Card - Youdle', player)),
    'GoyleLevel': lambda state, player: state.has('Goyle Level Key', player),
    'GryffindorChallenge': lambda state, player: state.has('Gryffindor Challenge Key', player),
    'Hogwarts': lambda state, player: True,
    'Quidditch': lambda state, player: state.has('Quidditch Key', player),
    'RictusempraChallenge': lambda state, player: state.has('Rictusempra Challenge Key', player),
    'SkurgeChallenge': lambda state, player: state.has('Skurge Challenge Key', player)  and  state.has('Skurge', player),
    'SlytherinCommon': lambda state, player: state.has('Slytherin Common Room Key', player),
    'SpongifyChallenge': lambda state, player: state.has('Spongify Challenge Key', player),
    'WhompingWillow': lambda state, player: state.has('Whomping Willow Key', player)  and  state.has('Spongify', player),
}
