"""AUTO-GENERATED by scripts/gen_apworld.py from data/logic.yaml. Do not edit by hand."""

from typing import Callable

from BaseClasses import CollectionState

# Per-location additional rules. Location is reachable iff its region's
# entry rule passes AND this rule passes. Locations not listed here have no
# extra requirement (the region's entry rule alone gates reachability).
LOCATION_RULES: dict[str, Callable[[CollectionState, int], bool]] = {
}

# goal_name -> list of location names that must be reachable for victory.
# Player picks one via the YAML `goal:` option (default `basilisk` for v1).
GOAL_REQUIREMENTS: dict[str, list[str]] = {
    'basilisk': ['LevelClear_ChamberOfSecrets'],
}
