"""AUTO-GENERATED by scripts/gen_apworld.py from data/logic.yaml. Do not edit by hand."""

from typing import Callable

from BaseClasses import CollectionState

# Per-location additional rules. Location is reachable iff its region's
# entry rule passes AND this rule passes. Locations not listed here have no
# extra requirement (the region's entry rule alone gates reachability).
LOCATION_RULES: dict[str, Callable[[CollectionState, int], bool]] = {
    'Card_Alderton': lambda state, player: state.has('Alohomora', player)  and  state.has('Spongify', player),
    'Card_Andros': lambda state, player: state.has('Alohomora', player),
    'Card_Barkwith': lambda state, player: state.has('Alohomora', player)  and  state.has('Rictusempra', player),
    'Card_Belby': lambda state, player: state.has('Alohomora', player),
    'Card_Blane': lambda state, player: state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player),
    'Card_Bonham': lambda state, player: state.has('Alohomora', player),
    'Card_Catchlove': lambda state, player: state.has('Alohomora', player),
    'Card_Dodderidge': lambda state, player: state.has('Alohomora', player),
    'Card_Ethelred': lambda state, player: state.has('Alohomora', player),
    'Card_Fulbert': lambda state, player: state.has('Alohomora', player),
    'Card_Gunhilda': lambda state, player: state.has('Alohomora', player),
    'Card_Hipworth': lambda state, player: state.has('Alohomora', player),
    'Card_Jones': lambda state, player: state.has('Alohomora', player)  and  state.has('Diffindo', player),
    'Card_Kegg': lambda state, player: state.has('Alohomora', player),
    'Card_Lufkin': lambda state, player: state.has('Alohomora', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player)  and  state.has('Spongify', player),
    'Card_Maeve': lambda state, player: state.has('Alohomora', player),
    'Card_Marjoribanks': lambda state, player: state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player),
    'Card_Montmorency': lambda state, player: state.has('Alohomora', player)  and  state.has('Skurge', player),
    'Card_Mopsus': lambda state, player: state.has('Alohomora', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player),
    'Card_Oglethorpe': lambda state, player: state.has('Alohomora', player)  and  state.has('Spongify', player)  and  state.has('Diffindo', player),
    'Card_Oldridge': lambda state, player: state.has('Spongify', player),
    'Card_Plunkett': lambda state, player: state.has('Alohomora', player)  and  state.has('Diffindo', player),
    'Card_Pokeby': lambda state, player: state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player),
    'Card_Sawbridge': lambda state, player: state.has('Alohomora', player),
    'Card_Shingleton': lambda state, player: state.has('Alohomora', player)  and  state.has('Skurge', player),
    'Card_Sykes': lambda state, player: state.has('Spongify', player),
    'Card_Toothill': lambda state, player: state.has('Spongify', player),
    'Card_Twonk': lambda state, player: state.has('Alohomora', player)  and  state.has('Diffindo', player),
    'Card_Vablatsky': lambda state, player: state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player),
    'Card_Wadcock': lambda state, player: state.has('Alohomora', player),
    'Card_Wendelin': lambda state, player: state.has('Alohomora', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player),
    'Card_Wenlock': lambda state, player: state.has('Alohomora', player),
    'Card_Wright': lambda state, player: state.has('Alohomora', player)  and  state.has('Diffindo', player),
    'Card_Youdle': lambda state, player: state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player),
    'Classroom_Flitwick_Skurge': lambda state, player: state.has('Rictusempra', player)  and  state.has('Skurge', player),
    'Classroom_Lockhart_Rictusempra': lambda state, player: state.has('Rictusempra', player),
    'Classroom_Lockhart_Spongify': lambda state, player: state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player),
    'Classroom_Sprout_Diffindo': lambda state, player: state.has('Alohomora', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Diffindo', player),
}

# goal_name -> direct item/logic rule for victory generation.
# Runtime completion still comes from the game-side GOAL_COMPLETE signal.
GOAL_RULES: dict[str, Callable[[CollectionState, int], bool]] = {
    'basilisk': lambda state, player: state.has('Flipendo', player)  and  state.has('Lumos', player)  and  state.has('Alohomora', player)  and  state.has('Diffindo', player)  and  state.has('Rictusempra', player)  and  state.has('Skurge', player)  and  state.has('Spongify', player),
}

# Optional goal_name -> location names that must be reachable for victory.
GOAL_LOCATION_REQUIREMENTS: dict[str, list[str]] = {
}
