from .access import (_Access, _bronze_cards, alohomora, bicorn_level_key,
                     boomslang_level_key, chamber_of_secrets_key, diffindo,
                     flipendo, forbidden_forest_key, goyle_level_key, lumos,
                     rictusempra, running, skurge, slytherin_common_room_key,
                     spongify)

# Chamber of Secrets level logic (both modes): the drop in needs Spongify to land
# safely, but this many bronze cards (two extra health rows) tank the 2.5-row fall
# instead. Only this first fall is bronze-skippable; deeper gates keep bare spongify.
# Vanilla masks it (region entry already needs Spongify, bronze not progression there).
CHAMBER_FALL_BRONZE_COUNT = 20
chamber_first_fall = spongify | _bronze_cards(CHAMBER_FALL_BRONZE_COUNT)

# Open castle is the base table: every location's open castle access rule.
# Vanilla is derived from it below (open castle plus the extra gating vanilla
# adds), so the two modes cannot drift apart.
LOCATION_RULES_OPEN_CASTLE: dict[str, _Access] = {
    # The bean room opens its containers with Alohomora in both modes.
    # Vanilla makes it a one-shot timed visit (missable); the rule is the same.
    "Bean Bonus Room - Chest 1": alohomora,
    "Bean Bonus Room - Chest 2": alohomora,
    "Bean Bonus Room - Chest 3": alohomora,
    "Bean Bonus Room - Chest 4": alohomora,
    "Bean Bonus Room - Chest 5": alohomora,
    "Bean Bonus Room - Chest 6": alohomora,
    "Bean Bonus Room - Gargoyle": alohomora,
    "Bicorn Level - Card Agrippa": alohomora & flipendo & skurge & rictusempra,
    "Bicorn Level - Card Cronk": alohomora & (flipendo | running) & skurge,
    "Bicorn Level - Card Goshawk": alohomora & flipendo & skurge & rictusempra,
    "Bicorn Level - Card Nutcombe": alohomora & flipendo & skurge & rictusempra,
    "Bicorn Level - Card Peakes": alohomora & (flipendo | running) & skurge,
    "Bicorn Level - Card Stump": alohomora & flipendo & skurge & rictusempra,
    "Bicorn Level - Cauldron 1": alohomora & flipendo,
    "Bicorn Level - Cauldron 2": alohomora & flipendo,
    "Bicorn Level - Cauldron 3": alohomora & flipendo & rictusempra & lumos,
    "Bicorn Level - Cauldron 4": alohomora & flipendo & rictusempra & skurge,
    "Bicorn Level - Cauldron 5": alohomora & flipendo & rictusempra & skurge,
    "Bicorn Level - Cauldron 6": alohomora & flipendo & rictusempra & skurge,
    "Bicorn Level - Chest 1": alohomora & flipendo & skurge,
    "Bicorn Level - Chest 2": alohomora & flipendo & skurge,
    "Bicorn Level - Chest 3": alohomora & flipendo & rictusempra,
    "Bicorn Level - Chest 5": alohomora & flipendo & rictusempra & skurge & lumos,
    "Bicorn Level - Chest 6": alohomora & flipendo & rictusempra & skurge,
    "Bicorn Level - Chest 7": alohomora & flipendo & rictusempra & skurge,
    "Bicorn Level - Chest 8": alohomora & flipendo & rictusempra & skurge,
    "Bicorn Level - Chest 9": alohomora & flipendo & rictusempra & skurge,
    "Bicorn Level - Complete": alohomora & flipendo & skurge & rictusempra,
    "Bicorn Level - Flobberworm Mucous Jar 1": alohomora & flipendo & rictusempra & skurge,
    "Bicorn Level - Flobberworm Mucous Jar 2": alohomora & flipendo & rictusempra & skurge,
    "Bicorn Level - Chest 4": alohomora & flipendo & rictusempra & skurge,
    "Bicorn Level - Secret 1": alohomora & (flipendo | running) & skurge,
    "Bicorn Level - Secret 2": alohomora & flipendo & skurge & rictusempra,
    "Bicorn Level - Secret 3": alohomora & flipendo & skurge & rictusempra,
    "Bicorn Level - Secret 4": alohomora & flipendo & skurge & rictusempra,
    "Bicorn Level - Secret 5": alohomora & flipendo & skurge & rictusempra,
    "Bicorn Level - Secret 6": alohomora & flipendo & skurge & lumos & rictusempra,
    "Bicorn Level - Secret 7": alohomora & flipendo & skurge & rictusempra,
    "Bicorn Level - Wiggentree Bark Jar 1": alohomora & flipendo,
    "Bicorn Level - Wiggentree Bark Jar 2": alohomora & flipendo & rictusempra & skurge,
    "Boomslang Level - Card Toke": diffindo & alohomora,
    "Boomslang Level - Card Tugwood": diffindo & flipendo & lumos & alohomora,
    "Boomslang Level - Chest": diffindo & alohomora,
    "Boomslang Level - Complete": diffindo,
    "Boomslang Level - Flobberworm Mucous Jar": diffindo & flipendo,
    "Boomslang Level - Oil Can 1": diffindo & flipendo,
    "Boomslang Level - Oil Can 2": diffindo & flipendo,
    "Boomslang Level - Oil Can 3": diffindo & flipendo,
    "Boomslang Level - Plant Pot 1": diffindo & flipendo,
    "Boomslang Level - Plant Pot 2": diffindo & flipendo,
    "Boomslang Level - Plant Pot 3": diffindo & flipendo,
    "Boomslang Level - Plant Pot 4": diffindo & flipendo,
    "Boomslang Level - Plant Pot 5": diffindo & flipendo,
    "Boomslang Level - Plant Pot 6": diffindo & flipendo,
    "Boomslang Level - Secret 1": diffindo & flipendo,
    "Boomslang Level - Secret 2": diffindo & flipendo & lumos,
    "Boomslang Level - Secret 3": diffindo & alohomora,
    "Castle Exterior - Card Marjoribanks": diffindo & alohomora,
    "Castle Exterior - Card Oglethorpe": alohomora & diffindo & lumos & spongify,
    "Castle Exterior - Card Plunkett": alohomora & diffindo & lumos,
    "Castle Exterior - Card Pokeby": alohomora,
    "Castle Exterior - Card Sykes": spongify,
    "Castle Exterior - Card Twonk": alohomora & diffindo,
    "Castle Exterior - Card Wadcock": alohomora,
    "Castle Exterior - Card Youdle": (flipendo | spongify | running) & alohomora,
    "Castle Exterior - Chest 1": alohomora,
    "Castle Exterior - Chest 2": alohomora,
    "Castle Exterior - Chest 3": alohomora,
    "Castle Exterior - Chest 4": diffindo & alohomora,
    "Castle Exterior - Chest 5": alohomora,
    "Castle Exterior - Chest 6": alohomora,
    "Castle Exterior - Chest 7": alohomora,
    "Castle Exterior - Chest 8": alohomora,
    "Castle Exterior - Chest 9": alohomora,
    "Castle Exterior - Secret 1": alohomora & diffindo,
    "Castle Exterior - Secret 2": alohomora,
    "Castle Exterior - Secret 3": alohomora & diffindo & lumos,
    "Castle Exterior - Secret 4": alohomora & diffindo & spongify & lumos,
    "Castle Exterior - Secret 5": spongify,
    "Castle Exterior - Secret 6": flipendo | spongify | running,
    "Castle Exterior - Secret 7": diffindo,
    "Castle Exterior - Secret 8": alohomora,
    "Chamber of Secrets - Card Elphick": spongify & diffindo & skurge & rictusempra & flipendo,
    "Chamber of Secrets - Cauldron 1": chamber_first_fall & flipendo,
    "Chamber of Secrets - Cauldron 10": spongify & diffindo & skurge & rictusempra & flipendo,
    "Chamber of Secrets - Cauldron 2": chamber_first_fall & flipendo,
    "Chamber of Secrets - Cauldron 3": spongify & diffindo & skurge & flipendo,
    "Chamber of Secrets - Cauldron 4": spongify & diffindo & skurge & flipendo,
    "Chamber of Secrets - Cauldron 5": spongify & diffindo & skurge & flipendo,
    "Chamber of Secrets - Cauldron 6": spongify & diffindo & skurge & flipendo,
    "Chamber of Secrets - Cauldron 7": spongify & diffindo & skurge & flipendo,
    "Chamber of Secrets - Cauldron 8": spongify & diffindo & skurge & rictusempra & flipendo,
    "Chamber of Secrets - Cauldron 9": spongify & diffindo & skurge & rictusempra & flipendo,
    "Chamber of Secrets - Chest 1": skurge & lumos & alohomora,
    "Chamber of Secrets - Chest 2": chamber_first_fall & alohomora,
    "Chamber of Secrets - Chest 3": chamber_first_fall & alohomora,
    "Chamber of Secrets - Chest 4": spongify & diffindo & skurge & alohomora,
    "Chamber of Secrets - Chest 5": spongify & diffindo & skurge & alohomora,
    "Chamber of Secrets - Chest 6": spongify & diffindo & skurge & (flipendo | running) & alohomora,
    "Chamber of Secrets - Chest 7": spongify & diffindo & skurge & rictusempra & flipendo & lumos & alohomora,
    "Chamber of Secrets - Complete": spongify & diffindo & skurge & rictusempra & flipendo,
    "Chamber of Secrets - Flobberworm Mucous Jar 1": chamber_first_fall & flipendo,
    "Chamber of Secrets - Flobberworm Mucous Jar 2": spongify & diffindo & skurge & rictusempra & flipendo,
    "Chamber of Secrets - Flobberworm Mucous Jar 3": spongify & diffindo & skurge & rictusempra & flipendo,
    "Chamber of Secrets - Secret 1": skurge & lumos,
    "Chamber of Secrets - Secret 2": spongify & diffindo & skurge,
    "Chamber of Secrets - Secret 3": spongify & diffindo & skurge & (flipendo | running),
    "Chamber of Secrets - Secret 4": spongify & diffindo & skurge & rictusempra & flipendo,
    "Chamber of Secrets - Secret 5": spongify & diffindo & skurge & rictusempra & flipendo & lumos,
    "Chamber of Secrets - Secret 6": spongify & diffindo & skurge & rictusempra & flipendo,
    "Chamber of Secrets - Wiggentree Bark Jar 1": chamber_first_fall & flipendo,
    "Chamber of Secrets - Wiggentree Bark Jar 2": spongify & diffindo & skurge & rictusempra & flipendo,
    "Chamber of Secrets - Wiggentree Bark Jar 3": spongify & diffindo & skurge & rictusempra & flipendo,
    "Diffindo Challenge - Beat Par Time": diffindo & rictusempra & flipendo & lumos & skurge & alohomora,
    "Diffindo Challenge - Card Ketteridge": diffindo & rictusempra & flipendo & skurge & alohomora,
    "Diffindo Challenge - Card Merwyn": diffindo & rictusempra & flipendo & alohomora,
    "Diffindo Challenge - Card Shimpling": diffindo & rictusempra & flipendo & lumos & alohomora,
    "Diffindo Challenge - Card Smethwyck": flipendo & alohomora,
    "Diffindo Challenge - Card Stalk": diffindo & rictusempra & flipendo & (skurge | running) & alohomora,
    "Diffindo Challenge - Card Thurkell": diffindo & rictusempra & flipendo & skurge & lumos & alohomora,
    "Diffindo Challenge - Card Ulric": diffindo & rictusempra & flipendo & lumos & alohomora,
    "Diffindo Challenge - Card Withers": diffindo & rictusempra & flipendo & skurge & alohomora,
    "Diffindo Challenge - Cauldron 1": flipendo,
    "Diffindo Challenge - Cauldron 2": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Cauldron 3": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Cauldron 4": diffindo & rictusempra & (skurge | running) & flipendo,
    "Diffindo Challenge - Cauldron 5": diffindo & rictusempra & skurge & flipendo,
    "Diffindo Challenge - Cauldron 6": diffindo & rictusempra & skurge & flipendo,
    "Diffindo Challenge - Cauldron 7": diffindo & rictusempra & skurge & flipendo,
    "Diffindo Challenge - Challenge Star 1": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Challenge Star 10": diffindo & rictusempra & flipendo & (skurge | running) & alohomora,
    "Diffindo Challenge - Challenge Star 11": diffindo & rictusempra & flipendo & (skurge | running) & alohomora,
    "Diffindo Challenge - Challenge Star 12": diffindo & rictusempra & flipendo & skurge,
    "Diffindo Challenge - Challenge Star 13": diffindo & rictusempra & flipendo & skurge,
    "Diffindo Challenge - Challenge Star 14": diffindo & rictusempra & flipendo & skurge & lumos,
    "Diffindo Challenge - Challenge Star 2": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Challenge Star 3": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Challenge Star 4": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Challenge Star 5": diffindo & rictusempra & flipendo & lumos,
    "Diffindo Challenge - Challenge Star 6": diffindo & rictusempra & flipendo & lumos,
    "Diffindo Challenge - Challenge Star 7": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Challenge Star 8": diffindo & rictusempra & flipendo & (skurge | running),
    "Diffindo Challenge - Challenge Star 9": diffindo & rictusempra & flipendo & (skurge | running),
    "Diffindo Challenge - Chest 1": alohomora,
    "Diffindo Challenge - Chest 2": alohomora,
    "Diffindo Challenge - Chest 3": alohomora,
    "Diffindo Challenge - Chest 5": diffindo & rictusempra & flipendo & (skurge | running) & alohomora,
    "Diffindo Challenge - Chest 6": diffindo & rictusempra & flipendo & skurge & lumos & alohomora,
    "Diffindo Challenge - Complete": diffindo & rictusempra & flipendo & lumos & skurge,
    "Diffindo Challenge - Flobberworm Mucous Jar 1": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Flobberworm Mucous Jar 2": diffindo & rictusempra & (skurge | running) & alohomora & flipendo,
    "Diffindo Challenge - Flobberworm Mucous Jar 3": diffindo & rictusempra & (skurge | running) & flipendo,
    "Diffindo Challenge - Flobberworm Mucous Jar 4": diffindo & rictusempra & skurge & lumos & flipendo,
    "Diffindo Challenge - Jewel Box": diffindo & rictusempra & flipendo & alohomora,
    "Diffindo Challenge - Knight 1": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Knight 2": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Oil Can 1": flipendo,
    "Diffindo Challenge - Oil Can 2": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Oil Can 3": diffindo & rictusempra & (skurge | running) & flipendo,
    "Diffindo Challenge - Oil Can 4": diffindo & rictusempra & (skurge | running) & flipendo,
    "Diffindo Challenge - Chest 4": diffindo & rictusempra & flipendo & alohomora,
    "Diffindo Challenge - Plant Pot 1": flipendo,
    "Diffindo Challenge - Plant Pot 10": diffindo & rictusempra & skurge & lumos & flipendo,
    "Diffindo Challenge - Plant Pot 2": flipendo,
    "Diffindo Challenge - Plant Pot 3": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Plant Pot 4": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Plant Pot 5": diffindo & rictusempra & (skurge | running) & alohomora & flipendo,
    "Diffindo Challenge - Plant Pot 6": diffindo & rictusempra & (skurge | running) & alohomora & flipendo,
    "Diffindo Challenge - Plant Pot 7": diffindo & rictusempra & (skurge | running) & flipendo,
    "Diffindo Challenge - Plant Pot 8": diffindo & rictusempra & skurge & flipendo,
    "Diffindo Challenge - Plant Pot 9": diffindo & rictusempra & skurge & lumos & flipendo,
    "Diffindo Challenge - Secret 1": alohomora,
    "Diffindo Challenge - Secret 10": diffindo & rictusempra & flipendo & skurge & alohomora,
    "Diffindo Challenge - Secret 11": diffindo & rictusempra & flipendo & skurge & alohomora & lumos,
    "Diffindo Challenge - Secret 2": flipendo,
    "Diffindo Challenge - Secret 3": diffindo & rictusempra & flipendo,
    "Diffindo Challenge - Secret 4": diffindo & rictusempra & flipendo & lumos,
    "Diffindo Challenge - Secret 5": diffindo & rictusempra & flipendo & lumos,
    "Diffindo Challenge - Secret 6": diffindo & rictusempra & flipendo & lumos,
    "Diffindo Challenge - Secret 7": diffindo & rictusempra & flipendo & (skurge | running) & alohomora,
    "Diffindo Challenge - Secret 8": diffindo & rictusempra & flipendo & (skurge | running) & alohomora,
    "Diffindo Challenge - Secret 9": diffindo & rictusempra & flipendo & skurge & alohomora,
    "Dumbledore's Study - Card Beamish": flipendo,
    "Dumbledore's Study - Card Muldoon": alohomora,
    "Dumbledore's Study - Chest": alohomora,
    "Dumbledore's Study - Cigar Box": alohomora,
    "Dumbledore's Study - Decanter": flipendo,
    "Dumbledore's Study - Secret": flipendo,
    "Entry Hall - Card Alderton": alohomora & spongify,
    "Entry Hall - Card Andros": alohomora & flipendo,
    "Entry Hall - Card Dodderidge": alohomora,
    "Entry Hall - Card Gunhilda": alohomora,
    "Entry Hall - Card Jones": flipendo & diffindo & alohomora,
    "Entry Hall - Card Montmorency": alohomora & skurge,
    "Entry Hall - Card Mopsus": alohomora & skurge & diffindo,
    "Entry Hall - Card Sawbridge": alohomora,
    "Entry Hall - Card Shingleton": alohomora & lumos & skurge,
    "Entry Hall - Card Wendelin": lumos & diffindo & alohomora,
    "Entry Hall - Card Wright": alohomora & diffindo,
    "Entry Hall - Chest 1": alohomora,
    "Entry Hall - Chest 2": alohomora,
    "Entry Hall - Chest 3": alohomora,
    "Entry Hall - Chest 4": alohomora & spongify,
    "Entry Hall - Chest 5": alohomora,
    "Entry Hall - Chest 6": alohomora,
    "Entry Hall - Chest 7": alohomora,
    "Entry Hall - Chest 8": alohomora,
    "Entry Hall - Flobberworm Mucous Jar": flipendo,
    "Entry Hall - Knight 1": flipendo,
    "Entry Hall - Knight 2": flipendo,
    "Entry Hall - Knight 3": flipendo,
    "Entry Hall - Knight 4": flipendo,
    "Entry Hall - Secret 1": lumos & skurge,
    "Entry Hall - Secret 10": flipendo,
    "Entry Hall - Secret 11": alohomora,
    "Entry Hall - Secret 12": spongify,
    "Entry Hall - Secret 2": alohomora & skurge,
    "Entry Hall - Secret 3": (skurge | alohomora) & lumos & diffindo,
    "Entry Hall - Secret 4": alohomora,
    "Entry Hall - Secret 5": alohomora,
    "Entry Hall - Secret 6": alohomora,
    "Entry Hall - Secret 7": alohomora,
    "Entry Hall - Secret 8": diffindo,
    "Entry Hall - Secret 9": diffindo & flipendo,
    "Entry Hall - Wiggentree Bark Jar": flipendo,
    "Forbidden Forest - Card Cliodne": (lumos & spongify | running) & flipendo & alohomora,
    "Forbidden Forest - Card Fancourt": lumos & spongify & diffindo & alohomora,
    "Forbidden Forest - Card Oliphant": lumos & spongify & diffindo & rictusempra & alohomora,
    "Forbidden Forest - Card Ollerton": lumos & spongify & diffindo,
    "Forbidden Forest - Card Scamander": lumos & spongify & diffindo & alohomora,
    "Forbidden Forest - Card Wellbeloved": lumos & spongify & diffindo & flipendo & alohomora,
    "Forbidden Forest - Chest 1": lumos & spongify & diffindo & alohomora,
    "Forbidden Forest - Chest 2": lumos & spongify & diffindo & alohomora,
    "Forbidden Forest - Chest 3": lumos & spongify & diffindo & flipendo & alohomora,
    "Forbidden Forest - Complete": lumos & spongify & diffindo & flipendo & rictusempra,
    "Forbidden Forest - Flobberworm Mucous Jar 1": lumos & spongify & diffindo & flipendo,
    "Forbidden Forest - Flobberworm Mucous Jar 2": lumos & spongify & diffindo & flipendo,
    "Forbidden Forest - Secret 1": (lumos & spongify | running) & flipendo,
    "Forbidden Forest - Secret 2": lumos & spongify & diffindo & rictusempra,
    "Forbidden Forest - Secret 3": lumos & spongify & diffindo,
    "Forbidden Forest - Secret 4": lumos & spongify & diffindo,
    "Gold Card Room - Card Bott": rictusempra | spongify,
    "Gold Card Room - Card Dumbledore": alohomora & (rictusempra | spongify),
    "Gold Card Room - Card Gryffindor": alohomora & diffindo & (rictusempra | spongify),
    "Gold Card Room - Card Herpo": alohomora & diffindo & (rictusempra | spongify),
    "Gold Card Room - Card Hufflepuff": alohomora & diffindo & skurge & (rictusempra | spongify),
    "Gold Card Room - Card Knightley": alohomora & diffindo & skurge & (rictusempra | spongify),
    "Gold Card Room - Card Paracelsus": alohomora & diffindo & skurge & (rictusempra | spongify),
    "Gold Card Room - Card Pinkstone": alohomora & diffindo & skurge & (rictusempra | spongify),
    "Gold Card Room - Card Potter": alohomora & diffindo & skurge & (rictusempra | spongify),
    "Gold Card Room - Card Ravenclaw": alohomora & diffindo & skurge & (rictusempra | spongify),
    "Gold Card Room - Card Slytherin": alohomora & diffindo & (rictusempra | spongify),
    "Gold Card Room - Complete": alohomora & diffindo & skurge & (rictusempra | spongify),
    "Goyle Level - Card Bloxam": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Card Circe": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Card Plumpton": alohomora,
    "Goyle Level - Card Stroulger": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Card Whitehorn": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Card Wildsmith": diffindo & lumos & alohomora,
    "Goyle Level - Cauldron 1": diffindo & rictusempra & flipendo,
    "Goyle Level - Cauldron 2": diffindo & rictusempra & flipendo,
    "Goyle Level - Cauldron 3": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Cauldron 4": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Chest 1": diffindo & alohomora,
    "Goyle Level - Chest 11": diffindo & rictusempra & flipendo & lumos & alohomora,
    "Goyle Level - Chest 2": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Chest 3": diffindo & rictusempra & flipendo & lumos & alohomora,
    "Goyle Level - Chest 4": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Chest 5": diffindo & rictusempra & flipendo & lumos & alohomora,
    "Goyle Level - Chest 6": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Chest 8": diffindo & rictusempra & flipendo & lumos & alohomora,
    "Goyle Level - Chest 9": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Chest 10": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Complete": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Flobberworm Mucous Jar": diffindo & rictusempra & flipendo,
    "Goyle Level - Chest 7": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Secret 1": diffindo & lumos,
    "Goyle Level - Secret 2": diffindo & rictusempra & flipendo,
    "Goyle Level - Secret 3": diffindo & rictusempra & flipendo & lumos,
    "Goyle Level - Secret 4": diffindo & rictusempra & flipendo & lumos & alohomora,
    "Goyle Level - Secret 5": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Secret 6": diffindo & rictusempra & flipendo & lumos,
    "Goyle Level - Secret 7": diffindo & rictusempra & flipendo & alohomora,
    "Goyle Level - Secret 8": diffindo & rictusempra & flipendo & alohomora & lumos,
    "Grand Staircase - Card Barkwith": alohomora,
    "Grand Staircase - Card Blane": alohomora,
    "Grand Staircase - Card Bonham": alohomora,
    "Grand Staircase - Card Ethelred": alohomora,
    "Grand Staircase - Card Hipworth": alohomora,
    "Grand Staircase - Card Lufkin": alohomora & skurge & diffindo,
    "Grand Staircase - Card Maeve": alohomora & flipendo,
    "Grand Staircase - Card Oldridge": spongify & alohomora,
    "Grand Staircase - Card Toothill": spongify,
    "Grand Staircase - Card Vablatsky": chamber_of_secrets_key & alohomora,
    "Grand Staircase - Cauldron 1": flipendo,
    "Grand Staircase - Cauldron 2": flipendo,
    "Grand Staircase - Cauldron 3": flipendo,
    "Grand Staircase - Cauldron 4": flipendo,
    "Grand Staircase - Cauldron 5": flipendo,
    "Grand Staircase - Cauldron 6": flipendo,
    "Grand Staircase - Cauldron 7": flipendo,
    "Grand Staircase - Cauldron 8": flipendo,
    "Grand Staircase - Chest 1": alohomora,
    "Grand Staircase - Chest 2": alohomora,
    "Grand Staircase - Chest 3": alohomora & spongify,
    "Grand Staircase - Chest 4": alohomora,
    "Grand Staircase - Chest 5": alohomora,
    "Grand Staircase - Chest 6": alohomora & skurge & diffindo,
    "Grand Staircase - Chest 7": alohomora,
    "Grand Staircase - Cigar Box 1": alohomora,
    "Grand Staircase - Cigar Box 2": alohomora,
    "Grand Staircase - Decanter 1": flipendo,
    "Grand Staircase - Decanter 2": flipendo,
    "Grand Staircase - Jewel Box 1": alohomora,
    "Grand Staircase - Jewel Box 2": alohomora,
    "Grand Staircase - Knight": flipendo,
    "Grand Staircase - Music Box": alohomora,
    "Grand Staircase - Secret 1": alohomora,
    "Grand Staircase - Secret 2": alohomora,
    "Grand Staircase - Secret 3": alohomora,
    "Grand Staircase - Secret 4": flipendo,
    "Grand Staircase - Secret 5": spongify,
    "Grand Staircase - Secret 6": alohomora & skurge & diffindo,
    "Grand Staircase - Secret 8": alohomora,
    "Grand Staircase - Secret 9": alohomora,
    "Gryffindor Challenge - Cauldron 1": (diffindo | running) & spongify & flipendo,
    "Gryffindor Challenge - Cauldron 2": (diffindo | running) & spongify & flipendo,
    "Gryffindor Challenge - Cauldron 3": diffindo & spongify & alohomora & flipendo,
    "Gryffindor Challenge - Cauldron 4": diffindo & spongify & alohomora & flipendo,
    "Gryffindor Challenge - Cauldron 5": diffindo & spongify & alohomora & flipendo,
    "Gryffindor Challenge - Challenge Star 10": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Challenge Star 2": (diffindo | running) & spongify,
    "Gryffindor Challenge - Challenge Star 3": diffindo & spongify & alohomora,
    "Gryffindor Challenge - Challenge Star 4": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Challenge Star 5": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Challenge Star 6": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Challenge Star 7": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Challenge Star 8": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Challenge Star 9": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 1": alohomora,
    "Gryffindor Challenge - Chest 10": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 11": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 12": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 13": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 14": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 15": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 16": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 17": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 18": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 19": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 2": alohomora,
    "Gryffindor Challenge - Chest 20": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 21": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 22": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 3": (diffindo | running) & alohomora,
    "Gryffindor Challenge - Chest 4": (diffindo | running) & spongify & alohomora,
    "Gryffindor Challenge - Chest 5": diffindo & spongify & alohomora,
    "Gryffindor Challenge - Chest 6": diffindo & spongify & alohomora,
    "Gryffindor Challenge - Chest 7": diffindo & spongify & alohomora,
    "Gryffindor Challenge - Chest 8": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Chest 9": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Complete": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Secret 1": (diffindo | running) & spongify & alohomora,
    "Gryffindor Challenge - Secret 2": (diffindo | running) & spongify & alohomora,
    "Gryffindor Challenge - Secret 3": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Secret 4": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Secret 5": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Secret 6": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Secret 7": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Secret 8": diffindo & spongify & alohomora & (flipendo | running),
    "Gryffindor Challenge - Secret 9": diffindo & spongify & alohomora & (flipendo | running),
    "Rictusempra Challenge - Beat Par Time": rictusempra & flipendo & alohomora & lumos,
    "Rictusempra Challenge - Card Barbary": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Card Chittock": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Card Crumb": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Card Duke": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Card Graves": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Card Thruston": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Card Tremlett": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Card Wagtail": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Card Wintringham": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Cauldron 1": rictusempra & flipendo,
    "Rictusempra Challenge - Cauldron 2": rictusempra & flipendo,
    "Rictusempra Challenge - Cauldron 3": rictusempra & flipendo,
    "Rictusempra Challenge - Cauldron 4": rictusempra & flipendo,
    "Rictusempra Challenge - Cauldron 5": rictusempra & flipendo,
    "Rictusempra Challenge - Challenge Star 1": rictusempra & flipendo,
    "Rictusempra Challenge - Challenge Star 10": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Challenge Star 2": rictusempra & flipendo,
    "Rictusempra Challenge - Challenge Star 3": rictusempra & flipendo,
    "Rictusempra Challenge - Challenge Star 4": rictusempra & flipendo,
    "Rictusempra Challenge - Challenge Star 5": rictusempra & flipendo & alohomora & lumos,
    "Rictusempra Challenge - Challenge Star 6": rictusempra & flipendo,
    "Rictusempra Challenge - Challenge Star 7": rictusempra & flipendo,
    "Rictusempra Challenge - Challenge Star 8": rictusempra & flipendo,
    "Rictusempra Challenge - Challenge Star 9": rictusempra & flipendo,
    "Rictusempra Challenge - Chest 1": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Chest 2": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Chest 3": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Chest 4": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Chest 5": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Chest 6": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Complete": flipendo & rictusempra,
    "Rictusempra Challenge - Secret 1": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Secret 2": rictusempra & flipendo & alohomora & lumos,
    "Rictusempra Challenge - Secret 3": rictusempra & flipendo,
    "Rictusempra Challenge - Secret 4": rictusempra & flipendo & lumos,
    "Rictusempra Challenge - Secret 5": rictusempra & flipendo & alohomora,
    "Rictusempra Challenge - Secret 6": rictusempra & flipendo,
    "Rictusempra Challenge - Secret 7": rictusempra & flipendo & alohomora,
    "Skurge Challenge - Beat Par Time": skurge & flipendo & lumos & alohomora,
    "Skurge Challenge - Card Belby": skurge & flipendo & (lumos | running) & alohomora,
    "Skurge Challenge - Card Catchlove": skurge & flipendo & lumos & alohomora,
    "Skurge Challenge - Card Fulbert": skurge & flipendo & (lumos | running) & rictusempra & alohomora,
    "Skurge Challenge - Card Gregory": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Card Kegg": skurge & flipendo & (lumos | running) & alohomora,
    "Skurge Challenge - Card Wenlock": skurge & alohomora,
    "Skurge Challenge - Cauldron 1": skurge & flipendo,
    "Skurge Challenge - Cauldron 10": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Cauldron 11": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Cauldron 2": skurge & flipendo,
    "Skurge Challenge - Cauldron 3": skurge & flipendo,
    "Skurge Challenge - Cauldron 4": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Cauldron 5": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Cauldron 6": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Cauldron 7": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Cauldron 8": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Cauldron 9": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Challenge Star 1": skurge & (flipendo | running),
    "Skurge Challenge - Challenge Star 10": skurge & flipendo & lumos & alohomora,
    "Skurge Challenge - Challenge Star 2": skurge & (flipendo | running),
    "Skurge Challenge - Challenge Star 3": skurge & (flipendo | running) & alohomora,
    "Skurge Challenge - Challenge Star 4": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Challenge Star 5": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Challenge Star 6": skurge & flipendo & lumos & alohomora,
    "Skurge Challenge - Challenge Star 7": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Challenge Star 8": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Challenge Star 9": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Chest 1": skurge & alohomora & (flipendo | running),
    "Skurge Challenge - Chest 2": skurge & flipendo & lumos & alohomora,
    "Skurge Challenge - Chest 3": skurge & flipendo & (lumos | running) & alohomora,
    "Skurge Challenge - Chest 4": skurge & flipendo & (lumos | running) & alohomora,
    "Skurge Challenge - Chest 5": skurge & alohomora,
    "Skurge Challenge - Cigar Box": skurge & flipendo & (lumos | running) & alohomora,
    "Skurge Challenge - Complete": skurge & flipendo & lumos,
    "Skurge Challenge - Decanter 1": skurge & flipendo,
    "Skurge Challenge - Decanter 2": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Flobberworm Mucous Jar": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Jewel Box": skurge & flipendo & (lumos | running) & alohomora,
    "Skurge Challenge - Knight 1": flipendo,
    "Skurge Challenge - Knight 2": flipendo,
    "Skurge Challenge - Music Box": skurge & flipendo & (lumos | running) & alohomora,
    "Skurge Challenge - Chest 6": skurge & alohomora,
    "Skurge Challenge - Secret 1": skurge & alohomora,
    "Skurge Challenge - Secret 2": skurge & (flipendo | running) & alohomora,
    "Skurge Challenge - Secret 3": skurge & flipendo & lumos,
    "Skurge Challenge - Secret 4": skurge & flipendo & (lumos | running) & rictusempra,
    "Skurge Challenge - Secret 5": skurge & flipendo & (lumos | running) & alohomora,
    "Skurge Challenge - Secret 6": skurge & flipendo & (lumos | running),
    "Skurge Challenge - Secret 7": skurge & flipendo & lumos & alohomora,
    "Skurge Challenge - Wiggentree Bark Jar": skurge & flipendo & lumos & alohomora,
    "Slytherin Common Room - Card Clagg": flipendo & diffindo & alohomora,
    "Slytherin Common Room - Card Fay": flipendo & diffindo & (skurge | running) & lumos & alohomora,
    "Slytherin Common Room - Card Pilliwickle": flipendo & diffindo & (skurge | running) & lumos & alohomora,
    "Slytherin Common Room - Card Platt": flipendo & diffindo & (skurge | running) & lumos & alohomora,
    "Slytherin Common Room - Card Waffling": flipendo & diffindo & (skurge | running) & lumos & alohomora,
    "Slytherin Common Room - Cauldron 1": flipendo & diffindo & (skurge | running),
    "Slytherin Common Room - Cauldron 2": flipendo & diffindo & (skurge | running),
    "Slytherin Common Room - Chest 1": flipendo & diffindo & alohomora,
    "Slytherin Common Room - Chest 2": flipendo & diffindo & (skurge | running) & lumos & alohomora,
    "Slytherin Common Room - Chest 3": flipendo & diffindo & (skurge | running) & lumos & alohomora,
    "Slytherin Common Room - Chest 4": flipendo & diffindo & (skurge | running) & lumos & alohomora,
    "Slytherin Common Room - Complete": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Flobberworm Mucous Jar": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Knight 1": flipendo,
    "Slytherin Common Room - Knight 2": flipendo,
    "Slytherin Common Room - Knight 3": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Knight 4": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Knight 5": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Knight 6": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Knight 7": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Secret 1": flipendo & diffindo,
    "Slytherin Common Room - Secret 2": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Secret 3": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Secret 4": flipendo & diffindo & (skurge | running) & lumos & alohomora,
    "Slytherin Common Room - Secret 5": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Secret 6": flipendo & diffindo & (skurge | running) & lumos & alohomora,
    "Slytherin Common Room - Secret 7": flipendo & diffindo & (skurge | running) & lumos & alohomora,
    "Slytherin Common Room - Secret 8": flipendo & diffindo & (skurge | running) & lumos,
    "Slytherin Common Room - Wiggentree Bark Jar": flipendo & diffindo & (skurge | running) & lumos,
    "Spongify Challenge - Beat Par Time": spongify & skurge & flipendo & alohomora & lumos,
    "Spongify Challenge - Card Furmage": spongify & flipendo & rictusempra & alohomora,
    "Spongify Challenge - Card Grunnion": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Card Merlin": spongify & flipendo & lumos & alohomora,
    "Spongify Challenge - Card Po": spongify & lumos & alohomora & flipendo,
    "Spongify Challenge - Card Rastrick": spongify & flipendo & lumos & alohomora,
    "Spongify Challenge - Card Summerbee": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Card Warbeck": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Card Woodcroft": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Cauldron 1": flipendo,
    "Spongify Challenge - Cauldron 2": flipendo,
    "Spongify Challenge - Cauldron 3": spongify & flipendo & skurge,
    "Spongify Challenge - Cauldron 4": spongify & flipendo & skurge,
    "Spongify Challenge - Challenge Star 1": spongify,
    "Spongify Challenge - Challenge Star 10": spongify & flipendo & skurge,
    "Spongify Challenge - Challenge Star 2": spongify & alohomora,
    "Spongify Challenge - Challenge Star 3": spongify,
    "Spongify Challenge - Challenge Star 4": spongify & (flipendo | running),
    "Spongify Challenge - Challenge Star 5": spongify & flipendo,
    "Spongify Challenge - Challenge Star 6": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Challenge Star 7": spongify & flipendo & skurge,
    "Spongify Challenge - Challenge Star 8": spongify & flipendo & skurge,
    "Spongify Challenge - Challenge Star 9": spongify & flipendo & skurge,
    "Spongify Challenge - Chest 1": spongify & flipendo & alohomora,
    "Spongify Challenge - Chest 2": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Chest 3": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Chest 4": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Chest 5": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Chest 6": spongify & flipendo & skurge & lumos & alohomora,
    "Spongify Challenge - Chest 7": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Chest 9": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Cigar Box": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Complete": spongify & skurge & flipendo,
    "Spongify Challenge - Decanter 1": spongify & flipendo,
    "Spongify Challenge - Decanter 2": spongify & flipendo,
    "Spongify Challenge - Flobberworm Mucous Jar 1": spongify & flipendo & skurge,
    "Spongify Challenge - Flobberworm Mucous Jar 2": spongify & flipendo & skurge,
    "Spongify Challenge - Flobberworm Mucous Jar 3": spongify & flipendo & skurge,
    "Spongify Challenge - Music Box": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Chest 8": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Secret 1": spongify & flipendo & lumos,
    "Spongify Challenge - Secret 10": spongify & flipendo & skurge,
    "Spongify Challenge - Secret 11": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Secret 12": spongify & flipendo & skurge,
    "Spongify Challenge - Secret 13": spongify & flipendo & skurge & lumos,
    "Spongify Challenge - Secret 14": spongify & flipendo & skurge,
    "Spongify Challenge - Secret 15": spongify & flipendo & skurge,
    "Spongify Challenge - Secret 16": spongify & flipendo & skurge,
    "Spongify Challenge - Secret 2": spongify & flipendo & lumos & alohomora,
    "Spongify Challenge - Secret 3": spongify & flipendo,
    "Spongify Challenge - Secret 4": spongify & alohomora,
    "Spongify Challenge - Secret 5": spongify & lumos & flipendo,
    "Spongify Challenge - Secret 6": spongify & flipendo & rictusempra,
    "Spongify Challenge - Secret 7": spongify & flipendo & skurge,
    "Spongify Challenge - Secret 8": spongify & flipendo & skurge,
    "Spongify Challenge - Secret 9": spongify & flipendo & skurge & alohomora,
    "Spongify Challenge - Wiggentree Bark Jar 1": spongify & flipendo & skurge,
    "Spongify Challenge - Wiggentree Bark Jar 2": spongify & flipendo & skurge,
    "Spongify Challenge - Wiggentree Bark Jar 3": spongify & flipendo & skurge,
    "Whomping Willow - Card Starkey": lumos & flipendo,
    "Whomping Willow - Chest 1": alohomora,
    "Whomping Willow - Chest 2": lumos & alohomora,
    "Whomping Willow - Chest 3": lumos & alohomora,
    "Whomping Willow - Chest 4": lumos & flipendo & alohomora,
    "Whomping Willow - Complete": lumos & flipendo,
    "Whomping Willow - Knight 1": lumos & flipendo,
    "Whomping Willow - Knight 2": lumos & flipendo,
    "Whomping Willow - Secret 1": lumos & alohomora,
    "Whomping Willow - Secret 2": lumos & flipendo & alohomora,
    "Entry Hall - Witch Statue": flipendo,
    "Grand Staircase - Gregory the Smarmy Statue": flipendo,
    "Grand Staircase - Dragon Skeleton": flipendo,
    "Grand Staircase - Toilet": chamber_of_secrets_key & flipendo,
    "Castle Exterior - Dragon Statue": flipendo,
    "Castle Exterior - Plant Dragon 1": flipendo,
    "Castle Exterior - Plant Dragon 2": flipendo,
    "Skurge Challenge - Witch Statue": skurge & flipendo,
    "Whomping Willow - Dragon Statue": lumos & flipendo,
}

# Vanilla layers extra spell/key gating on top of the open castle rule: for
# these locations vanilla = the open castle rule AND the requirements here.
_VANILLA_EXTRA: dict[str, _Access] = {
    "Castle Exterior - Card Marjoribanks": rictusempra & skurge & bicorn_level_key | running,
    "Castle Exterior - Card Pokeby": rictusempra & skurge & bicorn_level_key | running,
    "Castle Exterior - Chest 8": skurge & rictusempra & bicorn_level_key | running,
    "Castle Exterior - Chest 9": skurge & rictusempra & diffindo & bicorn_level_key | running,
    "Castle Exterior - Secret 7": skurge & rictusempra & flipendo & bicorn_level_key | running,
    "Entry Hall - Card Gunhilda": rictusempra | skurge & diffindo,
    "Entry Hall - Card Montmorency": rictusempra | diffindo,
    "Entry Hall - Card Shingleton": rictusempra | diffindo,
    "Entry Hall - Card Wendelin": rictusempra | skurge,
    "Entry Hall - Chest 4": rictusempra | skurge & diffindo,
    "Entry Hall - Chest 5": rictusempra | skurge & diffindo,
    "Entry Hall - Chest 6": rictusempra | skurge & diffindo,
    "Entry Hall - Flobberworm Mucous Jar": rictusempra | skurge & diffindo,
    "Entry Hall - Knight 3": rictusempra | skurge & diffindo,
    "Entry Hall - Knight 4": rictusempra | skurge & diffindo,
    "Entry Hall - Secret 1": rictusempra | skurge & diffindo,
    "Entry Hall - Secret 2": rictusempra | skurge & diffindo,
    "Entry Hall - Secret 3": rictusempra | skurge & diffindo,
    "Entry Hall - Secret 4": rictusempra | skurge & diffindo,
    "Entry Hall - Wiggentree Bark Jar": rictusempra | skurge & diffindo,
    "Grand Staircase - Card Barkwith": rictusempra,
    "Grand Staircase - Card Blane": rictusempra & skurge,
    "Grand Staircase - Cauldron 3": rictusempra & skurge,
    "Grand Staircase - Cauldron 5": rictusempra & skurge,
    "Grand Staircase - Cigar Box 2": rictusempra & skurge,
    "Grand Staircase - Decanter 1": rictusempra,
    "Grand Staircase - Decanter 2": rictusempra,
    "Grand Staircase - Jewel Box 2": rictusempra,
    "Grand Staircase - Knight": rictusempra,
    "Grand Staircase - Music Box": rictusempra,
    "Grand Staircase - Dragon Skeleton": rictusempra,
    "Castle Exterior - Plant Dragon 1": skurge & rictusempra & alohomora & bicorn_level_key | running,
    "Castle Exterior - Plant Dragon 2": skurge & rictusempra & diffindo & alohomora & bicorn_level_key | running,
}

# Vanilla and open castle diverge here (open castle is not a relaxation of the
# vanilla rule), so vanilla states its rule in full.
_VANILLA_OVERRIDE: dict[str, _Access] = {
    "Castle Exterior - Card Youdle":
        alohomora & (rictusempra & skurge & flipendo & spongify & bicorn_level_key | running),
    "Castle Exterior - Secret 6": alohomora & skurge & rictusempra & flipendo & bicorn_level_key | running,
    "Grand Staircase - Card Vablatsky": alohomora & rictusempra & skurge,
    "Grand Staircase - Toilet": rictusempra & skurge & flipendo,
}

# Gated only in vanilla. Open castle has no per-location rule for these: the
# spell-learn checks do not exist there, and the vendors and Quidditch matches
# defer entirely to their region entry rule.
_VANILLA_ONLY: dict[str, _Access] = {
    "Castle Exterior - Card Vendor 1": alohomora & skurge & rictusempra & flipendo & bicorn_level_key | running,
    "Castle Exterior - Nimbus 2001": rictusempra,
    "Castle Exterior - Quidditch Armour": rictusempra,
    "Entry Hall - Ingredient Vendor 1": rictusempra,
    "Entry Hall - Ingredient Vendor 2": rictusempra | skurge & diffindo,
    "Entry Hall - Ingredient Vendor 3": rictusempra | skurge & diffindo,
    "Learned Diffindo": alohomora & rictusempra & skurge & diffindo & bicorn_level_key,
    "Learned Rictusempra": rictusempra,
    "Learned Skurge": rictusempra & skurge,
    "Learned Spongify": (
        alohomora & rictusempra & skurge & diffindo & spongify & bicorn_level_key
        & boomslang_level_key & goyle_level_key & slytherin_common_room_key),
    "Quidditch - Match 1 (Hufflepuff)": rictusempra,
    "Quidditch - Match 2 (Ravenclaw)": rictusempra & skurge,
    "Quidditch - Match 3 (Slytherin)": rictusempra & skurge & alohomora,
    "Quidditch - Match 4 (Hufflepuff)": rictusempra & skurge & diffindo & alohomora & bicorn_level_key,
    "Quidditch - Match 5 (Ravenclaw)": (
        rictusempra & skurge & diffindo & spongify & alohomora & bicorn_level_key
        & boomslang_level_key & goyle_level_key & slytherin_common_room_key),
    "Quidditch - Match 6 (Slytherin)": (
        rictusempra & skurge & diffindo & spongify & alohomora & bicorn_level_key
        & boomslang_level_key & goyle_level_key & slytherin_common_room_key),
}


def _build_vanilla() -> dict[str, _Access]:
    table = dict(LOCATION_RULES_OPEN_CASTLE)
    for name, extra in _VANILLA_EXTRA.items():
        table[name] = LOCATION_RULES_OPEN_CASTLE[name] & extra
    table.update(_VANILLA_OVERRIDE)
    table.update(_VANILLA_ONLY)
    return table


LOCATION_RULES_VANILLA: dict[str, _Access] = _build_vanilla()


GOAL_RULES_VANILLA: dict[str, _Access] = {
    "basilisk": flipendo
    & lumos
    & alohomora
    & diffindo
    & rictusempra
    & skurge
    & spongify
    & bicorn_level_key
    & boomslang_level_key
    & goyle_level_key
    & slytherin_common_room_key
    & forbidden_forest_key
    & chamber_of_secrets_key,
}

GOAL_LOCATION_REQUIREMENTS_VANILLA: dict[str, list[str]] = {}
