// AUTO-GENERATED by scripts/gen_apworld.py from data/items.yaml.
// Do not edit by hand. Re-run the generator after editing items.yaml.
class APCardMarker_WCDumbledore extends APCardMarker;

defaultproperties
{
    CardLocationId=101
    soundPickup=Sound'HPSounds.Magic_sfx.pickup_WC_gold'
    bVendorsCanSell=False
    strVendorOwnedAfterGState=""
    MarkerTier="Gold"
}
