// AUTO-GENERATED by scripts/gen_apworld.py from data/items.yaml.
// Do not edit by hand. Re-run the generator after editing items.yaml.
class APCardMarker_WCWright extends APCardMarker;

defaultproperties
{
    CardLocationId=35
}
