// AUTO-GENERATED by scripts/gen_apworld.py from data/items.yaml.
// Do not edit by hand. Re-run the generator after editing items.yaml.
class APCardMarker_WCPlumpton extends APCardMarker;

defaultproperties
{
    CardLocationId=83
    soundPickup=Sound'HPSounds.Magic_sfx.pickup_WC_bronze'
    bVendorsCanSell=True
    strVendorOwnedAfterGState="GSTATE110"
    MarkerTier="Bronze"
}
