// AUTO-GENERATED by scripts/gen_apworld.py from data/items.yaml.
// Do not edit by hand. Re-run the generator after editing items.yaml.
class APCardMarker_WCBeamish extends APCardMarker;

defaultproperties
{
    CardLocationId=79
    soundPickup=Sound'HPSounds.Magic_sfx.pickup_WC_silver'
    bVendorsCanSell=True
    strVendorOwnedAfterGState="GSTATE100"
    MarkerTier="Silver"
}
