//================================================================================
// APLogoMesh.
//
// The 3D plate shown on FOREIGN (non-HP2) Archipelago pickups. HP2-bound
// pickups morph to the real vanilla item instead and never use this mesh
// (see plans/03-marker-appearance-by-owner.md). One mesh, two skins:
//
//   APLogoTex0       9000 foreign plain  (filler / useful)
//   APLogoArrowTex0  9001 foreign arrow  (progression / trap)
//
// Both textures import here as named objects in the Skins group; the #3
// appearance resolver picks the slot-0 texture per marker at runtime. Nothing
// sets this mesh in defaultproperties -- it is applied only by the resolver.
//
// APLogoMesh.psk / APLogoAnims.psa are generated by tools/gen_logo_mesh.py
// (committed; generator not shipped). The one-frame anim exists only because
// this build's #exec Anim Import / Mesh DefaultAnim pipeline expects a
// sequence; the plate is static and the marker actor self-spins on Yaw.
//
// Mesh + skin pattern mirrors HP2UScriptDecompile/HPModels/Classes/skSnitch.uc.
// extends HPMesh: HPModels precedes HPArchipelago in Default.ini EditPackages.
//================================================================================

class APLogoMesh extends HPMesh
  Abstract;

//model import (APLogoMesh)
#exec Mesh ModelImport Mesh=APLogoMesh ModelFile=Models\APLogoMesh.psk LODStyle=10
#exec Mesh Origin Mesh=APLogoMesh X=0 Y=0 Z=0 Yaw=0 Pitch=0 Roll=0

//anim import (APLogoAnims)
#exec Anim Import Anim=APLogoAnims AnimFile=Models\APLogoAnims.psa Compress=1 MaxKeys=999999 ImportSeqs=1
#exec MeshMap Scale MeshMap=APLogoMesh X=1.0 Y=1.0 Z=1.0
#exec Mesh DefaultAnim Mesh=APLogoMesh Anim=APLogoAnims
#exec Anim Digest Anim=APLogoAnims VERBOSE

//texture import (APLogoTex0 = 9000 plain, APLogoArrowTex0 = 9001 arrow)
#exec Texture Import File=Textures\APLogoTex0.png Name=APLogoTex0 COMPRESSION=0 UPSCALE=1 Mips=1 Flags=0 Group=Skins
#exec Texture Import File=Textures\APLogoArrowTex0.png Name=APLogoArrowTex0 COMPRESSION=0 UPSCALE=1 Mips=1 Flags=0 Group=Skins
#exec MeshMap SetTexture MeshMap=APLogoMesh Num=0 Texture=APLogoTex0
