//================================================================================
// APLogoMesh.
//
// The 3D plate shown on FOREIGN (non-HP2) Archipelago pickups. HP2-bound
// pickups morph to the real vanilla item instead and never use this mesh.
// One mesh, two skins:
//
//   APLogoTex0       9000 foreign plain  (filler / useful)
//   APLogoArrowTex0  9001 foreign arrow  (progression / trap)
//
// Both textures import here as named objects in the Skins group; the #3
// appearance resolver picks the slot-0 texture per marker at runtime. Nothing
// sets this mesh in defaultproperties -- it is applied only by the resolver.
//
// Assets (APLogoMesh.psk / APLogoAnims.psa / the two PNGs) are generated by
// tools/gen_logo_mesh.py + gen_logo_textures.py (committed; generators not
// shipped). Geometry is one colour-matched 3D coin per logo orb. The one-frame
// anim exists only because #exec Anim Import expects a sequence; the marker
// actor self-spins on Yaw.
//
// Transparency uses a magenta chroma key, not alpha (alpha keying does not
// work in this build): P8 + Flags=2 + MaskedOverride magenta + STY_Masked
// (set in APCardWatcher.ApplyMeshSkin), the vanilla recipe used by
// skArmorHelmet / skTableVaseKO / Tree* sprites.
//
// UE1 re-import gotcha: editing the .psk/.png alone does not re-import. UCC
// only re-runs the #exec lines below when this .uc recompiles.
// scripts/rebuild_mod.ps1 deletes HPArchipelago.u before `ucc make` to force
// it; the asset-rev tag also dirties this file, so bump it on every asset
// change for non-clean builds.
// asset-rev: 13
//
// Mesh + skin pattern mirrors HP2UScriptDecompile/HPModels/Classes/skSnitch.uc.
// Extends HPMesh: HPModels precedes HPArchipelago in Default.ini EditPackages.
//================================================================================

class APLogoMesh extends HPMesh
  Abstract;

//model import (APLogoMesh)
#exec Mesh ModelImport Mesh=APLogoMesh ModelFile=Models\APLogoMesh.psk LODStyle=10
#exec Mesh Origin Mesh=APLogoMesh X=0 Y=0 Z=0 Yaw=0 Pitch=0 Roll=0

//anim import (APLogoAnims)
#exec Anim Import Anim=APLogoAnims AnimFile=Models\APLogoAnims.psa Compress=1 MaxKeys=999999 ImportSeqs=1
#exec MeshMap Scale MeshMap=APLogoMesh X=1.0 Y=1.0 Z=1.0
#exec Mesh DefaultAnim Mesh=APLogoMesh Anim=APLogoAnims
#exec Anim Digest Anim=APLogoAnims VERBOSE

//texture import (APLogoTex0 = 9000 plain, APLogoArrowTex0 = 9001 arrow)
//P8 + Flags=2 + MaskedOverride magenta + Style=STY_Masked: the proven vanilla
//transparent-skin recipe in this build (alpha channel does not key here).
#exec Texture Import File=Textures\APLogoTex0.png Name=APLogoTex0 COMPRESSION=P8 UPSCALE=1 Mips=1 Flags=2 MaskedOverride=(R=255,G=0,B=255,A=255) Group=Skins
#exec Texture Import File=Textures\APLogoArrowTex0.png Name=APLogoArrowTex0 COMPRESSION=P8 UPSCALE=1 Mips=1 Flags=2 MaskedOverride=(R=255,G=0,B=255,A=255) Group=Skins
#exec MeshMap SetTexture MeshMap=APLogoMesh Num=0 Texture=APLogoTex0
